// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetBlobRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlobRequest) Reset()         { *m = GetBlobRequest{} }
func (m *GetBlobRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlobRequest) ProtoMessage()    {}
func (*GetBlobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_761b0d99bd4e86bf, []int{0}
}
func (m *GetBlobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlobRequest.Unmarshal(m, b)
}
func (m *GetBlobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlobRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlobRequest.Merge(dst, src)
}
func (m *GetBlobRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlobRequest.Size(m)
}
func (m *GetBlobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlobRequest proto.InternalMessageInfo

func (m *GetBlobRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetBlobResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlobResponse) Reset()         { *m = GetBlobResponse{} }
func (m *GetBlobResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlobResponse) ProtoMessage()    {}
func (*GetBlobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_761b0d99bd4e86bf, []int{1}
}
func (m *GetBlobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlobResponse.Unmarshal(m, b)
}
func (m *GetBlobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlobResponse.Marshal(b, m, deterministic)
}
func (dst *GetBlobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlobResponse.Merge(dst, src)
}
func (m *GetBlobResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlobResponse.Size(m)
}
func (m *GetBlobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlobResponse proto.InternalMessageInfo

func (m *GetBlobResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PutBlobRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutBlobRequest) Reset()         { *m = PutBlobRequest{} }
func (m *PutBlobRequest) String() string { return proto.CompactTextString(m) }
func (*PutBlobRequest) ProtoMessage()    {}
func (*PutBlobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_761b0d99bd4e86bf, []int{2}
}
func (m *PutBlobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutBlobRequest.Unmarshal(m, b)
}
func (m *PutBlobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutBlobRequest.Marshal(b, m, deterministic)
}
func (dst *PutBlobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutBlobRequest.Merge(dst, src)
}
func (m *PutBlobRequest) XXX_Size() int {
	return xxx_messageInfo_PutBlobRequest.Size(m)
}
func (m *PutBlobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutBlobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutBlobRequest proto.InternalMessageInfo

func (m *PutBlobRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutBlobRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PutBlobResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutBlobResponse) Reset()         { *m = PutBlobResponse{} }
func (m *PutBlobResponse) String() string { return proto.CompactTextString(m) }
func (*PutBlobResponse) ProtoMessage()    {}
func (*PutBlobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_761b0d99bd4e86bf, []int{3}
}
func (m *PutBlobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutBlobResponse.Unmarshal(m, b)
}
func (m *PutBlobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutBlobResponse.Marshal(b, m, deterministic)
}
func (dst *PutBlobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutBlobResponse.Merge(dst, src)
}
func (m *PutBlobResponse) XXX_Size() int {
	return xxx_messageInfo_PutBlobResponse.Size(m)
}
func (m *PutBlobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutBlobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutBlobResponse proto.InternalMessageInfo

type DeleteBlobRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBlobRequest) Reset()         { *m = DeleteBlobRequest{} }
func (m *DeleteBlobRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBlobRequest) ProtoMessage()    {}
func (*DeleteBlobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_761b0d99bd4e86bf, []int{4}
}
func (m *DeleteBlobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlobRequest.Unmarshal(m, b)
}
func (m *DeleteBlobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlobRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteBlobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlobRequest.Merge(dst, src)
}
func (m *DeleteBlobRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBlobRequest.Size(m)
}
func (m *DeleteBlobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlobRequest proto.InternalMessageInfo

func (m *DeleteBlobRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteBlobResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBlobResponse) Reset()         { *m = DeleteBlobResponse{} }
func (m *DeleteBlobResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBlobResponse) ProtoMessage()    {}
func (*DeleteBlobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_761b0d99bd4e86bf, []int{5}
}
func (m *DeleteBlobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlobResponse.Unmarshal(m, b)
}
func (m *DeleteBlobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlobResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteBlobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlobResponse.Merge(dst, src)
}
func (m *DeleteBlobResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBlobResponse.Size(m)
}
func (m *DeleteBlobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlobResponse proto.InternalMessageInfo

type GetBlobKeysRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlobKeysRequest) Reset()         { *m = GetBlobKeysRequest{} }
func (m *GetBlobKeysRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlobKeysRequest) ProtoMessage()    {}
func (*GetBlobKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_761b0d99bd4e86bf, []int{6}
}
func (m *GetBlobKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlobKeysRequest.Unmarshal(m, b)
}
func (m *GetBlobKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlobKeysRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlobKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlobKeysRequest.Merge(dst, src)
}
func (m *GetBlobKeysRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlobKeysRequest.Size(m)
}
func (m *GetBlobKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlobKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlobKeysRequest proto.InternalMessageInfo

type GetBlobKeysResponse struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlobKeysResponse) Reset()         { *m = GetBlobKeysResponse{} }
func (m *GetBlobKeysResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlobKeysResponse) ProtoMessage()    {}
func (*GetBlobKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_761b0d99bd4e86bf, []int{7}
}
func (m *GetBlobKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlobKeysResponse.Unmarshal(m, b)
}
func (m *GetBlobKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlobKeysResponse.Marshal(b, m, deterministic)
}
func (dst *GetBlobKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlobKeysResponse.Merge(dst, src)
}
func (m *GetBlobKeysResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlobKeysResponse.Size(m)
}
func (m *GetBlobKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlobKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlobKeysResponse proto.InternalMessageInfo

func (m *GetBlobKeysResponse) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*GetBlobRequest)(nil), "storage.GetBlobRequest")
	proto.RegisterType((*GetBlobResponse)(nil), "storage.GetBlobResponse")
	proto.RegisterType((*PutBlobRequest)(nil), "storage.PutBlobRequest")
	proto.RegisterType((*PutBlobResponse)(nil), "storage.PutBlobResponse")
	proto.RegisterType((*DeleteBlobRequest)(nil), "storage.DeleteBlobRequest")
	proto.RegisterType((*DeleteBlobResponse)(nil), "storage.DeleteBlobResponse")
	proto.RegisterType((*GetBlobKeysRequest)(nil), "storage.GetBlobKeysRequest")
	proto.RegisterType((*GetBlobKeysResponse)(nil), "storage.GetBlobKeysResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageServiceClient interface {
	GetBlob(ctx context.Context, in *GetBlobRequest, opts ...grpc.CallOption) (*GetBlobResponse, error)
	PutBlob(ctx context.Context, in *PutBlobRequest, opts ...grpc.CallOption) (*PutBlobResponse, error)
	DeleteBlob(ctx context.Context, in *DeleteBlobRequest, opts ...grpc.CallOption) (*DeleteBlobResponse, error)
	GetBlobKeys(ctx context.Context, in *GetBlobKeysRequest, opts ...grpc.CallOption) (*GetBlobKeysResponse, error)
}

type storageServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorageServiceClient(cc *grpc.ClientConn) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) GetBlob(ctx context.Context, in *GetBlobRequest, opts ...grpc.CallOption) (*GetBlobResponse, error) {
	out := new(GetBlobResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/GetBlob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) PutBlob(ctx context.Context, in *PutBlobRequest, opts ...grpc.CallOption) (*PutBlobResponse, error) {
	out := new(PutBlobResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/PutBlob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteBlob(ctx context.Context, in *DeleteBlobRequest, opts ...grpc.CallOption) (*DeleteBlobResponse, error) {
	out := new(DeleteBlobResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/DeleteBlob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetBlobKeys(ctx context.Context, in *GetBlobKeysRequest, opts ...grpc.CallOption) (*GetBlobKeysResponse, error) {
	out := new(GetBlobKeysResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/GetBlobKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
type StorageServiceServer interface {
	GetBlob(context.Context, *GetBlobRequest) (*GetBlobResponse, error)
	PutBlob(context.Context, *PutBlobRequest) (*PutBlobResponse, error)
	DeleteBlob(context.Context, *DeleteBlobRequest) (*DeleteBlobResponse, error)
	GetBlobKeys(context.Context, *GetBlobKeysRequest) (*GetBlobKeysResponse, error)
}

func RegisterStorageServiceServer(s *grpc.Server, srv StorageServiceServer) {
	s.RegisterService(&_StorageService_serviceDesc, srv)
}

func _StorageService_GetBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/GetBlob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetBlob(ctx, req.(*GetBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_PutBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).PutBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/PutBlob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).PutBlob(ctx, req.(*PutBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/DeleteBlob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteBlob(ctx, req.(*DeleteBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetBlobKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlobKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetBlobKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/GetBlobKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetBlobKeys(ctx, req.(*GetBlobKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlob",
			Handler:    _StorageService_GetBlob_Handler,
		},
		{
			MethodName: "PutBlob",
			Handler:    _StorageService_PutBlob_Handler,
		},
		{
			MethodName: "DeleteBlob",
			Handler:    _StorageService_DeleteBlob_Handler,
		},
		{
			MethodName: "GetBlobKeys",
			Handler:    _StorageService_GetBlobKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_storage_761b0d99bd4e86bf) }

var fileDescriptor_storage_761b0d99bd4e86bf = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x2b, 0x86, 0xfe, 0x6a, 0x6a, 0xc7, 0x82, 0x21, 0xf5, 0x50, 0x16, 0x0a, 0xf5,
	0xd2, 0x83, 0x82, 0xa7, 0x9e, 0x44, 0x51, 0xf0, 0x22, 0xe9, 0x13, 0xa4, 0x3a, 0x88, 0xb4, 0xb8,
	0x35, 0xbb, 0x15, 0xf2, 0x30, 0xbe, 0xab, 0x98, 0x4c, 0xb7, 0x9b, 0xb6, 0xe4, 0x36, 0xc9, 0xcc,
	0xf7, 0x67, 0xe6, 0x23, 0x38, 0x33, 0x56, 0xe7, 0xd9, 0x07, 0x4f, 0x56, 0xb9, 0xb6, 0x9a, 0x42,
	0x79, 0x54, 0x0a, 0xd1, 0x13, 0xdb, 0xfb, 0xa5, 0x9e, 0xa7, 0xfc, 0xbd, 0x66, 0x63, 0xe9, 0x1c,
	0xed, 0x05, 0x17, 0x71, 0x30, 0x0c, 0xc6, 0x9d, 0xf4, 0xbf, 0x54, 0x23, 0x74, 0xdd, 0x8c, 0x59,
	0xe9, 0x2f, 0xc3, 0x44, 0x38, 0x7a, 0xcf, 0x6c, 0x56, 0x4e, 0x9d, 0xa6, 0x65, 0xad, 0xee, 0x10,
	0xbd, 0xae, 0x9b, 0xa3, 0x1c, 0xd7, 0xf2, 0xb8, 0x1e, 0xba, 0x8e, 0xab, 0xe2, 0xd5, 0x08, 0xbd,
	0x07, 0x5e, 0xb2, 0xe5, 0xe6, 0xc5, 0xfa, 0x20, 0x7f, 0x4c, 0xe0, 0x3e, 0x48, 0xd6, 0x7d, 0xe1,
	0xc2, 0x08, 0xad, 0xae, 0x71, 0x51, 0x7b, 0xbb, 0x3d, 0x64, 0xc1, 0x85, 0x89, 0x83, 0x61, 0x7b,
	0xdc, 0x49, 0xcb, 0xfa, 0xe6, 0xb7, 0x85, 0x68, 0x56, 0xf9, 0x99, 0x71, 0xfe, 0xf3, 0xf9, 0xc6,
	0x34, 0x45, 0x28, 0x34, 0x5d, 0x4e, 0x36, 0x2a, 0xeb, 0xe2, 0x92, 0x78, 0xbf, 0x21, 0x1f, 0x99,
	0x22, 0x94, 0x0b, 0x3d, 0xba, 0xee, 0xca, 0xa3, 0x77, 0x64, 0xd0, 0x23, 0xb0, 0xbd, 0x92, 0x12,
	0x37, 0xb7, 0x67, 0x28, 0x19, 0x1c, 0xec, 0x49, 0xcc, 0x33, 0x4e, 0x3c, 0x01, 0x34, 0xd8, 0xdd,
	0xd6, 0x93, 0x95, 0x5c, 0x1d, 0x6e, 0x56, 0x49, 0xf3, 0xe3, 0xf2, 0x1f, 0xba, 0xfd, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0xf4, 0xc8, 0x88, 0x08, 0x54, 0x02, 0x00, 0x00,
}
