// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetFileRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileRequest) Reset()         { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()    {}
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_67770c3923954988, []int{0}
}
func (m *GetFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileRequest.Unmarshal(m, b)
}
func (m *GetFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileRequest.Marshal(b, m, deterministic)
}
func (dst *GetFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileRequest.Merge(dst, src)
}
func (m *GetFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileRequest.Size(m)
}
func (m *GetFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileRequest proto.InternalMessageInfo

func (m *GetFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetFileResponse struct {
	File                 []byte   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileResponse) Reset()         { *m = GetFileResponse{} }
func (m *GetFileResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileResponse) ProtoMessage()    {}
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_67770c3923954988, []int{1}
}
func (m *GetFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileResponse.Unmarshal(m, b)
}
func (m *GetFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileResponse.Marshal(b, m, deterministic)
}
func (dst *GetFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileResponse.Merge(dst, src)
}
func (m *GetFileResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileResponse.Size(m)
}
func (m *GetFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileResponse proto.InternalMessageInfo

func (m *GetFileResponse) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type PutFileRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	File                 []byte   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutFileRequest) Reset()         { *m = PutFileRequest{} }
func (m *PutFileRequest) String() string { return proto.CompactTextString(m) }
func (*PutFileRequest) ProtoMessage()    {}
func (*PutFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_67770c3923954988, []int{2}
}
func (m *PutFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutFileRequest.Unmarshal(m, b)
}
func (m *PutFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutFileRequest.Marshal(b, m, deterministic)
}
func (dst *PutFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutFileRequest.Merge(dst, src)
}
func (m *PutFileRequest) XXX_Size() int {
	return xxx_messageInfo_PutFileRequest.Size(m)
}
func (m *PutFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutFileRequest proto.InternalMessageInfo

func (m *PutFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutFileRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type PutFileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutFileResponse) Reset()         { *m = PutFileResponse{} }
func (m *PutFileResponse) String() string { return proto.CompactTextString(m) }
func (*PutFileResponse) ProtoMessage()    {}
func (*PutFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_67770c3923954988, []int{3}
}
func (m *PutFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutFileResponse.Unmarshal(m, b)
}
func (m *PutFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutFileResponse.Marshal(b, m, deterministic)
}
func (dst *PutFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutFileResponse.Merge(dst, src)
}
func (m *PutFileResponse) XXX_Size() int {
	return xxx_messageInfo_PutFileResponse.Size(m)
}
func (m *PutFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutFileResponse proto.InternalMessageInfo

type DeleteFileRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileRequest) Reset()         { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()    {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_67770c3923954988, []int{4}
}
func (m *DeleteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileRequest.Unmarshal(m, b)
}
func (m *DeleteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileRequest.Merge(dst, src)
}
func (m *DeleteFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileRequest.Size(m)
}
func (m *DeleteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileRequest proto.InternalMessageInfo

func (m *DeleteFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteFileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileResponse) Reset()         { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()    {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_67770c3923954988, []int{5}
}
func (m *DeleteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResponse.Unmarshal(m, b)
}
func (m *DeleteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResponse.Merge(dst, src)
}
func (m *DeleteFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResponse.Size(m)
}
func (m *DeleteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResponse proto.InternalMessageInfo

type GetFileKeysRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileKeysRequest) Reset()         { *m = GetFileKeysRequest{} }
func (m *GetFileKeysRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileKeysRequest) ProtoMessage()    {}
func (*GetFileKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_67770c3923954988, []int{6}
}
func (m *GetFileKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileKeysRequest.Unmarshal(m, b)
}
func (m *GetFileKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileKeysRequest.Marshal(b, m, deterministic)
}
func (dst *GetFileKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileKeysRequest.Merge(dst, src)
}
func (m *GetFileKeysRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileKeysRequest.Size(m)
}
func (m *GetFileKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileKeysRequest proto.InternalMessageInfo

type GetFileKeysResponse struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileKeysResponse) Reset()         { *m = GetFileKeysResponse{} }
func (m *GetFileKeysResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileKeysResponse) ProtoMessage()    {}
func (*GetFileKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_67770c3923954988, []int{7}
}
func (m *GetFileKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileKeysResponse.Unmarshal(m, b)
}
func (m *GetFileKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileKeysResponse.Marshal(b, m, deterministic)
}
func (dst *GetFileKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileKeysResponse.Merge(dst, src)
}
func (m *GetFileKeysResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileKeysResponse.Size(m)
}
func (m *GetFileKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileKeysResponse proto.InternalMessageInfo

func (m *GetFileKeysResponse) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*GetFileRequest)(nil), "storage.GetFileRequest")
	proto.RegisterType((*GetFileResponse)(nil), "storage.GetFileResponse")
	proto.RegisterType((*PutFileRequest)(nil), "storage.PutFileRequest")
	proto.RegisterType((*PutFileResponse)(nil), "storage.PutFileResponse")
	proto.RegisterType((*DeleteFileRequest)(nil), "storage.DeleteFileRequest")
	proto.RegisterType((*DeleteFileResponse)(nil), "storage.DeleteFileResponse")
	proto.RegisterType((*GetFileKeysRequest)(nil), "storage.GetFileKeysRequest")
	proto.RegisterType((*GetFileKeysResponse)(nil), "storage.GetFileKeysResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageServiceClient interface {
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	PutFile(ctx context.Context, in *PutFileRequest, opts ...grpc.CallOption) (*PutFileResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	GetFileKeys(ctx context.Context, in *GetFileKeysRequest, opts ...grpc.CallOption) (*GetFileKeysResponse, error)
}

type storageServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorageServiceClient(cc *grpc.ClientConn) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/GetFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) PutFile(ctx context.Context, in *PutFileRequest, opts ...grpc.CallOption) (*PutFileResponse, error) {
	out := new(PutFileResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/PutFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetFileKeys(ctx context.Context, in *GetFileKeysRequest, opts ...grpc.CallOption) (*GetFileKeysResponse, error) {
	out := new(GetFileKeysResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/GetFileKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
type StorageServiceServer interface {
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	PutFile(context.Context, *PutFileRequest) (*PutFileResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	GetFileKeys(context.Context, *GetFileKeysRequest) (*GetFileKeysResponse, error)
}

func RegisterStorageServiceServer(s *grpc.Server, srv StorageServiceServer) {
	s.RegisterService(&_StorageService_serviceDesc, srv)
}

func _StorageService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_PutFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).PutFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/PutFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).PutFile(ctx, req.(*PutFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetFileKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetFileKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/GetFileKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetFileKeys(ctx, req.(*GetFileKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFile",
			Handler:    _StorageService_GetFile_Handler,
		},
		{
			MethodName: "PutFile",
			Handler:    _StorageService_PutFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _StorageService_DeleteFile_Handler,
		},
		{
			MethodName: "GetFileKeys",
			Handler:    _StorageService_GetFileKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_storage_67770c3923954988) }

var fileDescriptor_storage_67770c3923954988 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x2b, 0x86, 0x7e, 0x6a, 0x6a, 0xc7, 0x82, 0x21, 0xf5, 0x50, 0x16, 0x0a, 0xf5,
	0xd2, 0x83, 0x82, 0xa7, 0x1e, 0xfd, 0x07, 0x5e, 0x24, 0x7d, 0x02, 0x95, 0x51, 0x42, 0x83, 0xa9,
	0xd9, 0xad, 0x90, 0x87, 0xf1, 0x5d, 0xc5, 0xcd, 0xb8, 0xdd, 0xb4, 0x25, 0xb7, 0x49, 0x66, 0x7e,
	0x5f, 0x66, 0x7e, 0x04, 0x27, 0xda, 0x14, 0xe5, 0xcb, 0x07, 0xcf, 0x56, 0x65, 0x61, 0x0a, 0x0a,
	0xe5, 0x51, 0x29, 0x44, 0x0f, 0x6c, 0xee, 0xb3, 0x9c, 0x53, 0xfe, 0x5a, 0xb3, 0x36, 0x74, 0x8a,
	0xee, 0x92, 0xab, 0x38, 0x18, 0x07, 0xd3, 0x5e, 0xfa, 0x57, 0xaa, 0x09, 0xfa, 0x6e, 0x46, 0xaf,
	0x8a, 0x4f, 0xcd, 0x44, 0x38, 0x78, 0xcf, 0x72, 0xb6, 0x53, 0xc7, 0xa9, 0xad, 0xd5, 0x0d, 0xa2,
	0xe7, 0x75, 0x7b, 0x94, 0xe3, 0x3a, 0x1e, 0x37, 0x40, 0xdf, 0x71, 0x75, 0xbc, 0x9a, 0x60, 0x70,
	0xcb, 0x39, 0x1b, 0x6e, 0x5f, 0x6c, 0x08, 0xf2, 0xc7, 0x04, 0x1e, 0x82, 0x64, 0xdd, 0x27, 0xae,
	0xb4, 0xd0, 0xea, 0x12, 0x67, 0x8d, 0xb7, 0x9b, 0x43, 0x96, 0x5c, 0xe9, 0x38, 0x18, 0x77, 0xa7,
	0xbd, 0xd4, 0xd6, 0x57, 0x3f, 0x1d, 0x44, 0x8b, 0xda, 0xcf, 0x82, 0xcb, 0xef, 0xec, 0x8d, 0x69,
	0x8e, 0x50, 0x68, 0x3a, 0x9f, 0xfd, 0xab, 0x6c, 0x8a, 0x4b, 0xe2, 0xdd, 0x86, 0x7c, 0x64, 0x8e,
	0x50, 0x2e, 0xf4, 0xe8, 0xa6, 0x2b, 0x8f, 0xde, 0x92, 0x41, 0x77, 0xc0, 0xe6, 0x4a, 0x4a, 0xdc,
	0xdc, 0x8e, 0xa1, 0x64, 0xb4, 0xb7, 0x27, 0x31, 0x8f, 0x38, 0xf2, 0x04, 0xd0, 0x68, 0x7b, 0x5b,
	0x4f, 0x56, 0x72, 0xb1, 0xbf, 0x59, 0x27, 0xbd, 0x1e, 0xda, 0x7f, 0xe8, 0xfa, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x36, 0x67, 0x2e, 0xa0, 0x54, 0x02, 0x00, 0x00,
}
