// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package metadata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TODO (Franz): This should be encrypted; move this to
// the encryption server when its implemented
type FileMetadata struct {
	Created              *FileMetadata_UnixTimestamp `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	LastModified         *FileMetadata_UnixTimestamp `protobuf:"bytes,2,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	Permissions          string                      `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Size                 int64                       `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *FileMetadata) Reset()         { *m = FileMetadata{} }
func (m *FileMetadata) String() string { return proto.CompactTextString(m) }
func (*FileMetadata) ProtoMessage()    {}
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_e15e91970f204200, []int{0}
}
func (m *FileMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMetadata.Unmarshal(m, b)
}
func (m *FileMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMetadata.Marshal(b, m, deterministic)
}
func (dst *FileMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMetadata.Merge(dst, src)
}
func (m *FileMetadata) XXX_Size() int {
	return xxx_messageInfo_FileMetadata.Size(m)
}
func (m *FileMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_FileMetadata proto.InternalMessageInfo

func (m *FileMetadata) GetCreated() *FileMetadata_UnixTimestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *FileMetadata) GetLastModified() *FileMetadata_UnixTimestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

func (m *FileMetadata) GetPermissions() string {
	if m != nil {
		return m.Permissions
	}
	return ""
}

func (m *FileMetadata) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type FileMetadata_UnixTimestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanoseconds          int64    `protobuf:"varint,2,opt,name=nanoseconds,proto3" json:"nanoseconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileMetadata_UnixTimestamp) Reset()         { *m = FileMetadata_UnixTimestamp{} }
func (m *FileMetadata_UnixTimestamp) String() string { return proto.CompactTextString(m) }
func (*FileMetadata_UnixTimestamp) ProtoMessage()    {}
func (*FileMetadata_UnixTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_e15e91970f204200, []int{0, 0}
}
func (m *FileMetadata_UnixTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMetadata_UnixTimestamp.Unmarshal(m, b)
}
func (m *FileMetadata_UnixTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMetadata_UnixTimestamp.Marshal(b, m, deterministic)
}
func (dst *FileMetadata_UnixTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMetadata_UnixTimestamp.Merge(dst, src)
}
func (m *FileMetadata_UnixTimestamp) XXX_Size() int {
	return xxx_messageInfo_FileMetadata_UnixTimestamp.Size(m)
}
func (m *FileMetadata_UnixTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMetadata_UnixTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_FileMetadata_UnixTimestamp proto.InternalMessageInfo

func (m *FileMetadata_UnixTimestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *FileMetadata_UnixTimestamp) GetNanoseconds() int64 {
	if m != nil {
		return m.Nanoseconds
	}
	return 0
}

type GetDirectoryKeysRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDirectoryKeysRequest) Reset()         { *m = GetDirectoryKeysRequest{} }
func (m *GetDirectoryKeysRequest) String() string { return proto.CompactTextString(m) }
func (*GetDirectoryKeysRequest) ProtoMessage()    {}
func (*GetDirectoryKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_e15e91970f204200, []int{1}
}
func (m *GetDirectoryKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDirectoryKeysRequest.Unmarshal(m, b)
}
func (m *GetDirectoryKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDirectoryKeysRequest.Marshal(b, m, deterministic)
}
func (dst *GetDirectoryKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDirectoryKeysRequest.Merge(dst, src)
}
func (m *GetDirectoryKeysRequest) XXX_Size() int {
	return xxx_messageInfo_GetDirectoryKeysRequest.Size(m)
}
func (m *GetDirectoryKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDirectoryKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDirectoryKeysRequest proto.InternalMessageInfo

type GetDirectoryKeysResponse struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDirectoryKeysResponse) Reset()         { *m = GetDirectoryKeysResponse{} }
func (m *GetDirectoryKeysResponse) String() string { return proto.CompactTextString(m) }
func (*GetDirectoryKeysResponse) ProtoMessage()    {}
func (*GetDirectoryKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_e15e91970f204200, []int{2}
}
func (m *GetDirectoryKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDirectoryKeysResponse.Unmarshal(m, b)
}
func (m *GetDirectoryKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDirectoryKeysResponse.Marshal(b, m, deterministic)
}
func (dst *GetDirectoryKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDirectoryKeysResponse.Merge(dst, src)
}
func (m *GetDirectoryKeysResponse) XXX_Size() int {
	return xxx_messageInfo_GetDirectoryKeysResponse.Size(m)
}
func (m *GetDirectoryKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDirectoryKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDirectoryKeysResponse proto.InternalMessageInfo

func (m *GetDirectoryKeysResponse) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type GetMetadataRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMetadataRequest) Reset()         { *m = GetMetadataRequest{} }
func (m *GetMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*GetMetadataRequest) ProtoMessage()    {}
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_e15e91970f204200, []int{3}
}
func (m *GetMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetadataRequest.Unmarshal(m, b)
}
func (m *GetMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetadataRequest.Marshal(b, m, deterministic)
}
func (dst *GetMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetadataRequest.Merge(dst, src)
}
func (m *GetMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_GetMetadataRequest.Size(m)
}
func (m *GetMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetadataRequest proto.InternalMessageInfo

func (m *GetMetadataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetMetadataResponse struct {
	Metadata             *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetMetadataResponse) Reset()         { *m = GetMetadataResponse{} }
func (m *GetMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*GetMetadataResponse) ProtoMessage()    {}
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_e15e91970f204200, []int{4}
}
func (m *GetMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetadataResponse.Unmarshal(m, b)
}
func (m *GetMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetadataResponse.Marshal(b, m, deterministic)
}
func (dst *GetMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetadataResponse.Merge(dst, src)
}
func (m *GetMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_GetMetadataResponse.Size(m)
}
func (m *GetMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetadataResponse proto.InternalMessageInfo

func (m *GetMetadataResponse) GetMetadata() *FileMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SetMetadataRequest struct {
	Key                  string        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Metadata             *FileMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SetMetadataRequest) Reset()         { *m = SetMetadataRequest{} }
func (m *SetMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*SetMetadataRequest) ProtoMessage()    {}
func (*SetMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_e15e91970f204200, []int{5}
}
func (m *SetMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMetadataRequest.Unmarshal(m, b)
}
func (m *SetMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMetadataRequest.Marshal(b, m, deterministic)
}
func (dst *SetMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMetadataRequest.Merge(dst, src)
}
func (m *SetMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_SetMetadataRequest.Size(m)
}
func (m *SetMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetMetadataRequest proto.InternalMessageInfo

func (m *SetMetadataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetMetadataRequest) GetMetadata() *FileMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SetMetadataResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMetadataResponse) Reset()         { *m = SetMetadataResponse{} }
func (m *SetMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*SetMetadataResponse) ProtoMessage()    {}
func (*SetMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_e15e91970f204200, []int{6}
}
func (m *SetMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMetadataResponse.Unmarshal(m, b)
}
func (m *SetMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMetadataResponse.Marshal(b, m, deterministic)
}
func (dst *SetMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMetadataResponse.Merge(dst, src)
}
func (m *SetMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_SetMetadataResponse.Size(m)
}
func (m *SetMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetMetadataResponse proto.InternalMessageInfo

func (m *SetMetadataResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type GetFileRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileRequest) Reset()         { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()    {}
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_e15e91970f204200, []int{7}
}
func (m *GetFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileRequest.Unmarshal(m, b)
}
func (m *GetFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileRequest.Marshal(b, m, deterministic)
}
func (dst *GetFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileRequest.Merge(dst, src)
}
func (m *GetFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileRequest.Size(m)
}
func (m *GetFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileRequest proto.InternalMessageInfo

func (m *GetFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetFileResponse struct {
	FileChunk            []byte   `protobuf:"bytes,1,opt,name=file_chunk,json=fileChunk,proto3" json:"file_chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileResponse) Reset()         { *m = GetFileResponse{} }
func (m *GetFileResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileResponse) ProtoMessage()    {}
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_e15e91970f204200, []int{8}
}
func (m *GetFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileResponse.Unmarshal(m, b)
}
func (m *GetFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileResponse.Marshal(b, m, deterministic)
}
func (dst *GetFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileResponse.Merge(dst, src)
}
func (m *GetFileResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileResponse.Size(m)
}
func (m *GetFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileResponse proto.InternalMessageInfo

func (m *GetFileResponse) GetFileChunk() []byte {
	if m != nil {
		return m.FileChunk
	}
	return nil
}

type PutFileRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	FileChunk            []byte   `protobuf:"bytes,2,opt,name=file_chunk,json=fileChunk,proto3" json:"file_chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutFileRequest) Reset()         { *m = PutFileRequest{} }
func (m *PutFileRequest) String() string { return proto.CompactTextString(m) }
func (*PutFileRequest) ProtoMessage()    {}
func (*PutFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_e15e91970f204200, []int{9}
}
func (m *PutFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutFileRequest.Unmarshal(m, b)
}
func (m *PutFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutFileRequest.Marshal(b, m, deterministic)
}
func (dst *PutFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutFileRequest.Merge(dst, src)
}
func (m *PutFileRequest) XXX_Size() int {
	return xxx_messageInfo_PutFileRequest.Size(m)
}
func (m *PutFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutFileRequest proto.InternalMessageInfo

func (m *PutFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutFileRequest) GetFileChunk() []byte {
	if m != nil {
		return m.FileChunk
	}
	return nil
}

type PutFileResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutFileResponse) Reset()         { *m = PutFileResponse{} }
func (m *PutFileResponse) String() string { return proto.CompactTextString(m) }
func (*PutFileResponse) ProtoMessage()    {}
func (*PutFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_e15e91970f204200, []int{10}
}
func (m *PutFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutFileResponse.Unmarshal(m, b)
}
func (m *PutFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutFileResponse.Marshal(b, m, deterministic)
}
func (dst *PutFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutFileResponse.Merge(dst, src)
}
func (m *PutFileResponse) XXX_Size() int {
	return xxx_messageInfo_PutFileResponse.Size(m)
}
func (m *PutFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutFileResponse proto.InternalMessageInfo

func (m *PutFileResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type DeleteFileRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileRequest) Reset()         { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()    {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_e15e91970f204200, []int{11}
}
func (m *DeleteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileRequest.Unmarshal(m, b)
}
func (m *DeleteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileRequest.Merge(dst, src)
}
func (m *DeleteFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileRequest.Size(m)
}
func (m *DeleteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileRequest proto.InternalMessageInfo

func (m *DeleteFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteFileResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileResponse) Reset()         { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()    {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_e15e91970f204200, []int{12}
}
func (m *DeleteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResponse.Unmarshal(m, b)
}
func (m *DeleteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResponse.Merge(dst, src)
}
func (m *DeleteFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResponse.Size(m)
}
func (m *DeleteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResponse proto.InternalMessageInfo

func (m *DeleteFileResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func init() {
	proto.RegisterType((*FileMetadata)(nil), "metadata.FileMetadata")
	proto.RegisterType((*FileMetadata_UnixTimestamp)(nil), "metadata.FileMetadata.UnixTimestamp")
	proto.RegisterType((*GetDirectoryKeysRequest)(nil), "metadata.GetDirectoryKeysRequest")
	proto.RegisterType((*GetDirectoryKeysResponse)(nil), "metadata.GetDirectoryKeysResponse")
	proto.RegisterType((*GetMetadataRequest)(nil), "metadata.GetMetadataRequest")
	proto.RegisterType((*GetMetadataResponse)(nil), "metadata.GetMetadataResponse")
	proto.RegisterType((*SetMetadataRequest)(nil), "metadata.SetMetadataRequest")
	proto.RegisterType((*SetMetadataResponse)(nil), "metadata.SetMetadataResponse")
	proto.RegisterType((*GetFileRequest)(nil), "metadata.GetFileRequest")
	proto.RegisterType((*GetFileResponse)(nil), "metadata.GetFileResponse")
	proto.RegisterType((*PutFileRequest)(nil), "metadata.PutFileRequest")
	proto.RegisterType((*PutFileResponse)(nil), "metadata.PutFileResponse")
	proto.RegisterType((*DeleteFileRequest)(nil), "metadata.DeleteFileRequest")
	proto.RegisterType((*DeleteFileResponse)(nil), "metadata.DeleteFileResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetadataServiceClient interface {
	GetDirectoryKeys(ctx context.Context, in *GetDirectoryKeysRequest, opts ...grpc.CallOption) (*GetDirectoryKeysResponse, error)
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error)
	SetMetadata(ctx context.Context, in *SetMetadataRequest, opts ...grpc.CallOption) (*SetMetadataResponse, error)
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (MetadataService_GetFileClient, error)
	PutFile(ctx context.Context, opts ...grpc.CallOption) (MetadataService_PutFileClient, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
}

type metadataServiceClient struct {
	cc *grpc.ClientConn
}

func NewMetadataServiceClient(cc *grpc.ClientConn) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) GetDirectoryKeys(ctx context.Context, in *GetDirectoryKeysRequest, opts ...grpc.CallOption) (*GetDirectoryKeysResponse, error) {
	out := new(GetDirectoryKeysResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/GetDirectoryKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error) {
	out := new(GetMetadataResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/GetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) SetMetadata(ctx context.Context, in *SetMetadataRequest, opts ...grpc.CallOption) (*SetMetadataResponse, error) {
	out := new(SetMetadataResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/SetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (MetadataService_GetFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MetadataService_serviceDesc.Streams[0], "/metadata.MetadataService/GetFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &metadataServiceGetFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MetadataService_GetFileClient interface {
	Recv() (*GetFileResponse, error)
	grpc.ClientStream
}

type metadataServiceGetFileClient struct {
	grpc.ClientStream
}

func (x *metadataServiceGetFileClient) Recv() (*GetFileResponse, error) {
	m := new(GetFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *metadataServiceClient) PutFile(ctx context.Context, opts ...grpc.CallOption) (MetadataService_PutFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MetadataService_serviceDesc.Streams[1], "/metadata.MetadataService/PutFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &metadataServicePutFileClient{stream}
	return x, nil
}

type MetadataService_PutFileClient interface {
	Send(*PutFileRequest) error
	CloseAndRecv() (*PutFileResponse, error)
	grpc.ClientStream
}

type metadataServicePutFileClient struct {
	grpc.ClientStream
}

func (x *metadataServicePutFileClient) Send(m *PutFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *metadataServicePutFileClient) CloseAndRecv() (*PutFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PutFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *metadataServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
type MetadataServiceServer interface {
	GetDirectoryKeys(context.Context, *GetDirectoryKeysRequest) (*GetDirectoryKeysResponse, error)
	GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error)
	SetMetadata(context.Context, *SetMetadataRequest) (*SetMetadataResponse, error)
	GetFile(*GetFileRequest, MetadataService_GetFileServer) error
	PutFile(MetadataService_PutFileServer) error
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
}

func RegisterMetadataServiceServer(s *grpc.Server, srv MetadataServiceServer) {
	s.RegisterService(&_MetadataService_serviceDesc, srv)
}

func _MetadataService_GetDirectoryKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirectoryKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetDirectoryKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/GetDirectoryKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetDirectoryKeys(ctx, req.(*GetDirectoryKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/GetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_SetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).SetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/SetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).SetMetadata(ctx, req.(*SetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetadataServiceServer).GetFile(m, &metadataServiceGetFileServer{stream})
}

type MetadataService_GetFileServer interface {
	Send(*GetFileResponse) error
	grpc.ServerStream
}

type metadataServiceGetFileServer struct {
	grpc.ServerStream
}

func (x *metadataServiceGetFileServer) Send(m *GetFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _MetadataService_PutFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetadataServiceServer).PutFile(&metadataServicePutFileServer{stream})
}

type MetadataService_PutFileServer interface {
	SendAndClose(*PutFileResponse) error
	Recv() (*PutFileRequest, error)
	grpc.ServerStream
}

type metadataServicePutFileServer struct {
	grpc.ServerStream
}

func (x *metadataServicePutFileServer) SendAndClose(m *PutFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *metadataServicePutFileServer) Recv() (*PutFileRequest, error) {
	m := new(PutFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MetadataService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetadataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metadata.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDirectoryKeys",
			Handler:    _MetadataService_GetDirectoryKeys_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _MetadataService_GetMetadata_Handler,
		},
		{
			MethodName: "SetMetadata",
			Handler:    _MetadataService_SetMetadata_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _MetadataService_DeleteFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFile",
			Handler:       _MetadataService_GetFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PutFile",
			Handler:       _MetadataService_PutFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "metadata.proto",
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_metadata_e15e91970f204200) }

var fileDescriptor_metadata_e15e91970f204200 = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0xe5, 0xb8, 0x22, 0xcd, 0x49, 0x9a, 0x94, 0xa9, 0x04, 0xae, 0x69, 0x51, 0xb0, 0x00,
	0x79, 0x15, 0x95, 0x00, 0x5b, 0x04, 0xa2, 0x22, 0x2a, 0x55, 0x25, 0x34, 0x86, 0x05, 0x6c, 0x2a,
	0x63, 0x9f, 0x88, 0x51, 0x7c, 0x09, 0x9e, 0x31, 0x22, 0x3c, 0x0b, 0x2f, 0xc5, 0x1b, 0xa1, 0x71,
	0xc7, 0xf1, 0xd8, 0x75, 0xa2, 0x74, 0x37, 0x3e, 0x97, 0xef, 0xdc, 0x7e, 0x19, 0x86, 0x31, 0x0a,
	0x3f, 0xf4, 0x85, 0x3f, 0x59, 0x66, 0xa9, 0x48, 0xc9, 0x7e, 0xf9, 0xed, 0xfc, 0xed, 0xc0, 0xe0,
	0x03, 0x8b, 0xf0, 0x4a, 0x19, 0xc8, 0x1b, 0xe8, 0x06, 0x19, 0xfa, 0x02, 0x43, 0xcb, 0x18, 0x1b,
	0x6e, 0x7f, 0xfa, 0x74, 0xb2, 0x4e, 0xd6, 0x03, 0x27, 0x5f, 0x12, 0xf6, 0xfb, 0x33, 0x8b, 0x91,
	0x0b, 0x3f, 0x5e, 0xd2, 0x32, 0x89, 0x5c, 0xc0, 0x41, 0xe4, 0x73, 0x71, 0x1d, 0xa7, 0x21, 0x9b,
	0x33, 0x0c, 0xad, 0xce, 0x1d, 0x28, 0x03, 0x99, 0x7a, 0xa5, 0x32, 0xc9, 0x18, 0xfa, 0x4b, 0xcc,
	0x62, 0xc6, 0x39, 0x4b, 0x13, 0x6e, 0x99, 0x63, 0xc3, 0xed, 0x51, 0xdd, 0x44, 0x08, 0xec, 0x71,
	0xf6, 0x07, 0xad, 0xbd, 0xb1, 0xe1, 0x9a, 0xb4, 0x78, 0xdb, 0x97, 0x70, 0x50, 0x83, 0x12, 0x0b,
	0xba, 0x1c, 0x83, 0x34, 0x09, 0x79, 0x31, 0x91, 0x49, 0xcb, 0x4f, 0x59, 0x20, 0xf1, 0x93, 0xb4,
	0xf4, 0x76, 0x0a, 0xaf, 0x6e, 0x72, 0x8e, 0xe1, 0xe1, 0x0c, 0xc5, 0x39, 0xcb, 0x30, 0x10, 0x69,
	0xb6, 0xba, 0xc4, 0x15, 0xa7, 0xf8, 0x33, 0x47, 0x2e, 0x9c, 0x09, 0x58, 0xb7, 0x5d, 0x7c, 0x99,
	0x26, 0x1c, 0x65, 0x5f, 0x0b, 0x5c, 0xc9, 0x7a, 0xa6, 0xdb, 0xa3, 0xc5, 0xdb, 0x79, 0x0e, 0x64,
	0x86, 0xa2, 0x1c, 0x5c, 0x51, 0xc8, 0x21, 0x98, 0x0b, 0x5c, 0x15, 0x8d, 0xf5, 0xa8, 0x7c, 0x3a,
	0x17, 0x70, 0x54, 0x8b, 0x53, 0xc8, 0x29, 0xac, 0x8f, 0xa6, 0x0e, 0xf3, 0xa0, 0x7d, 0xa5, 0xb4,
	0x3a, 0xee, 0x37, 0x20, 0xde, 0x0e, 0x25, 0x6b, 0xec, 0xce, 0x8e, 0xec, 0xd7, 0x70, 0xe4, 0xb5,
	0xb4, 0xf9, 0x18, 0x80, 0xe7, 0x41, 0x80, 0x9c, 0xcf, 0xf3, 0xa8, 0xa8, 0xb1, 0x4f, 0x35, 0x8b,
	0xe3, 0xc0, 0x70, 0x86, 0x42, 0x32, 0x37, 0x6f, 0xe0, 0x0c, 0x46, 0xeb, 0x18, 0x85, 0x3d, 0x05,
	0x98, 0xb3, 0x08, 0xaf, 0x83, 0x1f, 0x79, 0xb2, 0x28, 0x62, 0x07, 0xb4, 0x27, 0x2d, 0xef, 0xa5,
	0xc1, 0x79, 0x07, 0xc3, 0x4f, 0xf9, 0x76, 0x6a, 0x03, 0xd1, 0x69, 0x22, 0x5e, 0xc0, 0x68, 0x8d,
	0xd8, 0x71, 0x96, 0x67, 0x70, 0xff, 0x1c, 0x23, 0x14, 0xb8, 0x7d, 0x9c, 0x57, 0x40, 0xf4, 0xb0,
	0xdd, 0xe0, 0xd3, 0x7f, 0x26, 0x8c, 0xca, 0xed, 0x7a, 0x98, 0xfd, 0x62, 0x01, 0x92, 0xaf, 0x70,
	0xd8, 0x94, 0x1c, 0x79, 0x52, 0x5d, 0x6a, 0x83, 0x52, 0x6d, 0x67, 0x5b, 0x88, 0x6a, 0xe7, 0x23,
	0xf4, 0x35, 0xd5, 0x91, 0x93, 0x5a, 0x4a, 0x43, 0x41, 0xf6, 0xe9, 0x06, 0x6f, 0xc5, 0xf2, 0xda,
	0x59, 0xde, 0x56, 0x56, 0x9b, 0x9e, 0xde, 0x42, 0x57, 0x69, 0x81, 0x58, 0xb5, 0xaa, 0xda, 0xce,
	0xed, 0xe3, 0x16, 0xcf, 0x4d, 0xfe, 0x99, 0x21, 0x09, 0xea, 0xb0, 0x3a, 0xa1, 0x2e, 0x17, 0x9d,
	0xd0, 0x50, 0x81, 0x6b, 0x90, 0x19, 0x40, 0x75, 0x40, 0xf2, 0xa8, 0x0a, 0xbd, 0x75, 0x7d, 0xfb,
	0xa4, 0xdd, 0x79, 0x83, 0xfa, 0x7e, 0xaf, 0xf8, 0xfb, 0xbe, 0xfc, 0x1f, 0x00, 0x00, 0xff, 0xff,
	0x24, 0xf7, 0xcb, 0x71, 0x8f, 0x05, 0x00, 0x00,
}
