// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package metadata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TODO: This should be encrypted; move this to
// the encryption layer when its implemented
type FileMetadata struct {
	Created              *FileMetadata_UnixTimestamp `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	LastModified         *FileMetadata_UnixTimestamp `protobuf:"bytes,2,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	Permissions          string                      `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Size                 int64                       `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *FileMetadata) Reset()         { *m = FileMetadata{} }
func (m *FileMetadata) String() string { return proto.CompactTextString(m) }
func (*FileMetadata) ProtoMessage()    {}
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_c2131e524d2df18b, []int{0}
}
func (m *FileMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMetadata.Unmarshal(m, b)
}
func (m *FileMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMetadata.Marshal(b, m, deterministic)
}
func (dst *FileMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMetadata.Merge(dst, src)
}
func (m *FileMetadata) XXX_Size() int {
	return xxx_messageInfo_FileMetadata.Size(m)
}
func (m *FileMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_FileMetadata proto.InternalMessageInfo

func (m *FileMetadata) GetCreated() *FileMetadata_UnixTimestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *FileMetadata) GetLastModified() *FileMetadata_UnixTimestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

func (m *FileMetadata) GetPermissions() string {
	if m != nil {
		return m.Permissions
	}
	return ""
}

func (m *FileMetadata) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type FileMetadata_UnixTimestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanoseconds          int64    `protobuf:"varint,2,opt,name=nanoseconds,proto3" json:"nanoseconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileMetadata_UnixTimestamp) Reset()         { *m = FileMetadata_UnixTimestamp{} }
func (m *FileMetadata_UnixTimestamp) String() string { return proto.CompactTextString(m) }
func (*FileMetadata_UnixTimestamp) ProtoMessage()    {}
func (*FileMetadata_UnixTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_c2131e524d2df18b, []int{0, 0}
}
func (m *FileMetadata_UnixTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMetadata_UnixTimestamp.Unmarshal(m, b)
}
func (m *FileMetadata_UnixTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMetadata_UnixTimestamp.Marshal(b, m, deterministic)
}
func (dst *FileMetadata_UnixTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMetadata_UnixTimestamp.Merge(dst, src)
}
func (m *FileMetadata_UnixTimestamp) XXX_Size() int {
	return xxx_messageInfo_FileMetadata_UnixTimestamp.Size(m)
}
func (m *FileMetadata_UnixTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMetadata_UnixTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_FileMetadata_UnixTimestamp proto.InternalMessageInfo

func (m *FileMetadata_UnixTimestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *FileMetadata_UnixTimestamp) GetNanoseconds() int64 {
	if m != nil {
		return m.Nanoseconds
	}
	return 0
}

type GetMetadataRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMetadataRequest) Reset()         { *m = GetMetadataRequest{} }
func (m *GetMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*GetMetadataRequest) ProtoMessage()    {}
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_c2131e524d2df18b, []int{1}
}
func (m *GetMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetadataRequest.Unmarshal(m, b)
}
func (m *GetMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetadataRequest.Marshal(b, m, deterministic)
}
func (dst *GetMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetadataRequest.Merge(dst, src)
}
func (m *GetMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_GetMetadataRequest.Size(m)
}
func (m *GetMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetadataRequest proto.InternalMessageInfo

func (m *GetMetadataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetMetadataResponse struct {
	Metadata             *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetMetadataResponse) Reset()         { *m = GetMetadataResponse{} }
func (m *GetMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*GetMetadataResponse) ProtoMessage()    {}
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_c2131e524d2df18b, []int{2}
}
func (m *GetMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetadataResponse.Unmarshal(m, b)
}
func (m *GetMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetadataResponse.Marshal(b, m, deterministic)
}
func (dst *GetMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetadataResponse.Merge(dst, src)
}
func (m *GetMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_GetMetadataResponse.Size(m)
}
func (m *GetMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetadataResponse proto.InternalMessageInfo

func (m *GetMetadataResponse) GetMetadata() *FileMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SetMetadataRequest struct {
	Key                  string        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Metadata             *FileMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SetMetadataRequest) Reset()         { *m = SetMetadataRequest{} }
func (m *SetMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*SetMetadataRequest) ProtoMessage()    {}
func (*SetMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_c2131e524d2df18b, []int{3}
}
func (m *SetMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMetadataRequest.Unmarshal(m, b)
}
func (m *SetMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMetadataRequest.Marshal(b, m, deterministic)
}
func (dst *SetMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMetadataRequest.Merge(dst, src)
}
func (m *SetMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_SetMetadataRequest.Size(m)
}
func (m *SetMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetMetadataRequest proto.InternalMessageInfo

func (m *SetMetadataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetMetadataRequest) GetMetadata() *FileMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SetMetadataResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMetadataResponse) Reset()         { *m = SetMetadataResponse{} }
func (m *SetMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*SetMetadataResponse) ProtoMessage()    {}
func (*SetMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_c2131e524d2df18b, []int{4}
}
func (m *SetMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMetadataResponse.Unmarshal(m, b)
}
func (m *SetMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMetadataResponse.Marshal(b, m, deterministic)
}
func (dst *SetMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMetadataResponse.Merge(dst, src)
}
func (m *SetMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_SetMetadataResponse.Size(m)
}
func (m *SetMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetMetadataResponse proto.InternalMessageInfo

func (m *SetMetadataResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type GetFileRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileRequest) Reset()         { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()    {}
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_c2131e524d2df18b, []int{5}
}
func (m *GetFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileRequest.Unmarshal(m, b)
}
func (m *GetFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileRequest.Marshal(b, m, deterministic)
}
func (dst *GetFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileRequest.Merge(dst, src)
}
func (m *GetFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileRequest.Size(m)
}
func (m *GetFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileRequest proto.InternalMessageInfo

func (m *GetFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetFileResponse struct {
	FileChunk            []byte   `protobuf:"bytes,1,opt,name=file_chunk,json=fileChunk,proto3" json:"file_chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileResponse) Reset()         { *m = GetFileResponse{} }
func (m *GetFileResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileResponse) ProtoMessage()    {}
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_c2131e524d2df18b, []int{6}
}
func (m *GetFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileResponse.Unmarshal(m, b)
}
func (m *GetFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileResponse.Marshal(b, m, deterministic)
}
func (dst *GetFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileResponse.Merge(dst, src)
}
func (m *GetFileResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileResponse.Size(m)
}
func (m *GetFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileResponse proto.InternalMessageInfo

func (m *GetFileResponse) GetFileChunk() []byte {
	if m != nil {
		return m.FileChunk
	}
	return nil
}

type PutFileRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	FileChunk            []byte   `protobuf:"bytes,2,opt,name=file_chunk,json=fileChunk,proto3" json:"file_chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutFileRequest) Reset()         { *m = PutFileRequest{} }
func (m *PutFileRequest) String() string { return proto.CompactTextString(m) }
func (*PutFileRequest) ProtoMessage()    {}
func (*PutFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_c2131e524d2df18b, []int{7}
}
func (m *PutFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutFileRequest.Unmarshal(m, b)
}
func (m *PutFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutFileRequest.Marshal(b, m, deterministic)
}
func (dst *PutFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutFileRequest.Merge(dst, src)
}
func (m *PutFileRequest) XXX_Size() int {
	return xxx_messageInfo_PutFileRequest.Size(m)
}
func (m *PutFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutFileRequest proto.InternalMessageInfo

func (m *PutFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutFileRequest) GetFileChunk() []byte {
	if m != nil {
		return m.FileChunk
	}
	return nil
}

type PutFileResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutFileResponse) Reset()         { *m = PutFileResponse{} }
func (m *PutFileResponse) String() string { return proto.CompactTextString(m) }
func (*PutFileResponse) ProtoMessage()    {}
func (*PutFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_c2131e524d2df18b, []int{8}
}
func (m *PutFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutFileResponse.Unmarshal(m, b)
}
func (m *PutFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutFileResponse.Marshal(b, m, deterministic)
}
func (dst *PutFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutFileResponse.Merge(dst, src)
}
func (m *PutFileResponse) XXX_Size() int {
	return xxx_messageInfo_PutFileResponse.Size(m)
}
func (m *PutFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutFileResponse proto.InternalMessageInfo

func (m *PutFileResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type DeleteFileRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileRequest) Reset()         { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()    {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_c2131e524d2df18b, []int{9}
}
func (m *DeleteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileRequest.Unmarshal(m, b)
}
func (m *DeleteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileRequest.Merge(dst, src)
}
func (m *DeleteFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileRequest.Size(m)
}
func (m *DeleteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileRequest proto.InternalMessageInfo

func (m *DeleteFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteFileResponse struct {
	Successful           string   `protobuf:"bytes,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileResponse) Reset()         { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()    {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_c2131e524d2df18b, []int{10}
}
func (m *DeleteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResponse.Unmarshal(m, b)
}
func (m *DeleteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResponse.Merge(dst, src)
}
func (m *DeleteFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResponse.Size(m)
}
func (m *DeleteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResponse proto.InternalMessageInfo

func (m *DeleteFileResponse) GetSuccessful() string {
	if m != nil {
		return m.Successful
	}
	return ""
}

func init() {
	proto.RegisterType((*FileMetadata)(nil), "metadata.FileMetadata")
	proto.RegisterType((*FileMetadata_UnixTimestamp)(nil), "metadata.FileMetadata.UnixTimestamp")
	proto.RegisterType((*GetMetadataRequest)(nil), "metadata.GetMetadataRequest")
	proto.RegisterType((*GetMetadataResponse)(nil), "metadata.GetMetadataResponse")
	proto.RegisterType((*SetMetadataRequest)(nil), "metadata.SetMetadataRequest")
	proto.RegisterType((*SetMetadataResponse)(nil), "metadata.SetMetadataResponse")
	proto.RegisterType((*GetFileRequest)(nil), "metadata.GetFileRequest")
	proto.RegisterType((*GetFileResponse)(nil), "metadata.GetFileResponse")
	proto.RegisterType((*PutFileRequest)(nil), "metadata.PutFileRequest")
	proto.RegisterType((*PutFileResponse)(nil), "metadata.PutFileResponse")
	proto.RegisterType((*DeleteFileRequest)(nil), "metadata.DeleteFileRequest")
	proto.RegisterType((*DeleteFileResponse)(nil), "metadata.DeleteFileResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageServiceClient interface {
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error)
	SetMetadata(ctx context.Context, in *SetMetadataRequest, opts ...grpc.CallOption) (*SetMetadataResponse, error)
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (StorageService_GetFileClient, error)
	PutFile(ctx context.Context, opts ...grpc.CallOption) (StorageService_PutFileClient, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
}

type storageServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorageServiceClient(cc *grpc.ClientConn) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error) {
	out := new(GetMetadataResponse)
	err := c.cc.Invoke(ctx, "/metadata.StorageService/GetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) SetMetadata(ctx context.Context, in *SetMetadataRequest, opts ...grpc.CallOption) (*SetMetadataResponse, error) {
	out := new(SetMetadataResponse)
	err := c.cc.Invoke(ctx, "/metadata.StorageService/SetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (StorageService_GetFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StorageService_serviceDesc.Streams[0], "/metadata.StorageService/GetFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageServiceGetFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StorageService_GetFileClient interface {
	Recv() (*GetFileResponse, error)
	grpc.ClientStream
}

type storageServiceGetFileClient struct {
	grpc.ClientStream
}

func (x *storageServiceGetFileClient) Recv() (*GetFileResponse, error) {
	m := new(GetFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageServiceClient) PutFile(ctx context.Context, opts ...grpc.CallOption) (StorageService_PutFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StorageService_serviceDesc.Streams[1], "/metadata.StorageService/PutFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageServicePutFileClient{stream}
	return x, nil
}

type StorageService_PutFileClient interface {
	Send(*PutFileRequest) error
	CloseAndRecv() (*PutFileResponse, error)
	grpc.ClientStream
}

type storageServicePutFileClient struct {
	grpc.ClientStream
}

func (x *storageServicePutFileClient) Send(m *PutFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storageServicePutFileClient) CloseAndRecv() (*PutFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PutFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, "/metadata.StorageService/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
type StorageServiceServer interface {
	GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error)
	SetMetadata(context.Context, *SetMetadataRequest) (*SetMetadataResponse, error)
	GetFile(*GetFileRequest, StorageService_GetFileServer) error
	PutFile(StorageService_PutFileServer) error
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
}

func RegisterStorageServiceServer(s *grpc.Server, srv StorageServiceServer) {
	s.RegisterService(&_StorageService_serviceDesc, srv)
}

func _StorageService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.StorageService/GetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_SetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).SetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.StorageService/SetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).SetMetadata(ctx, req.(*SetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).GetFile(m, &storageServiceGetFileServer{stream})
}

type StorageService_GetFileServer interface {
	Send(*GetFileResponse) error
	grpc.ServerStream
}

type storageServiceGetFileServer struct {
	grpc.ServerStream
}

func (x *storageServiceGetFileServer) Send(m *GetFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StorageService_PutFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServiceServer).PutFile(&storageServicePutFileServer{stream})
}

type StorageService_PutFileServer interface {
	SendAndClose(*PutFileResponse) error
	Recv() (*PutFileRequest, error)
	grpc.ServerStream
}

type storageServicePutFileServer struct {
	grpc.ServerStream
}

func (x *storageServicePutFileServer) SendAndClose(m *PutFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storageServicePutFileServer) Recv() (*PutFileRequest, error) {
	m := new(PutFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StorageService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.StorageService/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metadata.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetadata",
			Handler:    _StorageService_GetMetadata_Handler,
		},
		{
			MethodName: "SetMetadata",
			Handler:    _StorageService_SetMetadata_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _StorageService_DeleteFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFile",
			Handler:       _StorageService_GetFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PutFile",
			Handler:       _StorageService_PutFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "metadata.proto",
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_metadata_c2131e524d2df18b) }

var fileDescriptor_metadata_c2131e524d2df18b = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x86, 0x65, 0xa7, 0x22, 0xcd, 0x24, 0x4d, 0x61, 0x2a, 0x21, 0x13, 0x5a, 0x14, 0x59, 0x80,
	0x72, 0x8a, 0x4a, 0x80, 0x2b, 0x02, 0x81, 0x88, 0x5a, 0x54, 0x09, 0xad, 0xe1, 0xc2, 0xa5, 0x5a,
	0xec, 0x09, 0xac, 0x6a, 0x7b, 0x8d, 0x77, 0x8d, 0x80, 0xdf, 0xc2, 0xdf, 0xe4, 0x8e, 0xec, 0xfa,
	0x63, 0x9d, 0x3a, 0x51, 0x7a, 0xf3, 0xce, 0xc7, 0x33, 0x3b, 0xef, 0xbb, 0x32, 0x8c, 0x23, 0xd2,
	0x3c, 0xe0, 0x9a, 0xcf, 0x93, 0x54, 0x6a, 0x89, 0xfb, 0xd5, 0xd9, 0xfd, 0x6b, 0xc3, 0xe8, 0xbd,
	0x08, 0xe9, 0xa2, 0x0c, 0xe0, 0x2b, 0xe8, 0xfb, 0x29, 0x71, 0x4d, 0x81, 0x63, 0x4d, 0xad, 0xd9,
	0x70, 0xf1, 0x78, 0x5e, 0x37, 0x9b, 0x85, 0xf3, 0xcf, 0xb1, 0xf8, 0xf5, 0x49, 0x44, 0xa4, 0x34,
	0x8f, 0x12, 0x56, 0x35, 0xe1, 0x19, 0x1c, 0x84, 0x5c, 0xe9, 0xcb, 0x48, 0x06, 0x62, 0x25, 0x28,
	0x70, 0xec, 0x5b, 0x50, 0x46, 0x79, 0xeb, 0x45, 0xd9, 0x89, 0x53, 0x18, 0x26, 0x94, 0x46, 0x42,
	0x29, 0x21, 0x63, 0xe5, 0xf4, 0xa6, 0xd6, 0x6c, 0xc0, 0xcc, 0x10, 0x22, 0xec, 0x29, 0xf1, 0x87,
	0x9c, 0xbd, 0xa9, 0x35, 0xeb, 0xb1, 0xe2, 0x7b, 0xf2, 0x01, 0x0e, 0x5a, 0x50, 0x74, 0xa0, 0xaf,
	0xc8, 0x97, 0x71, 0xa0, 0x8a, 0x8d, 0x7a, 0xac, 0x3a, 0xe6, 0x03, 0x62, 0x1e, 0xcb, 0x2a, 0x6b,
	0x17, 0x59, 0x33, 0xe4, 0x3e, 0x05, 0x5c, 0x92, 0xae, 0x6e, 0xcb, 0xe8, 0x47, 0x46, 0x4a, 0xe3,
	0x5d, 0xe8, 0x5d, 0xd1, 0xef, 0x82, 0x36, 0x60, 0xf9, 0xa7, 0x7b, 0x06, 0x47, 0xad, 0x3a, 0x95,
	0xc8, 0x58, 0x11, 0x2e, 0xa0, 0x56, 0xba, 0x54, 0xf3, 0x7e, 0xb7, 0x0e, 0xac, 0x71, 0xe4, 0x0b,
	0xa0, 0xb7, 0xc3, 0xc8, 0x16, 0xdb, 0xde, 0x91, 0xfd, 0x12, 0x8e, 0xbc, 0x8e, 0x6b, 0x3e, 0x02,
	0x50, 0x99, 0xef, 0x93, 0x52, 0xab, 0x2c, 0x2c, 0x66, 0xec, 0x33, 0x23, 0xe2, 0xba, 0x30, 0x5e,
	0x92, 0xce, 0x99, 0x9b, 0x15, 0x38, 0x85, 0xc3, 0xba, 0xa6, 0xc4, 0x9e, 0x00, 0xac, 0x44, 0x48,
	0x97, 0xfe, 0xf7, 0x2c, 0xbe, 0x2a, 0x6a, 0x47, 0x6c, 0x90, 0x47, 0xde, 0xe6, 0x01, 0xf7, 0x0d,
	0x8c, 0x3f, 0x66, 0xdb, 0xa9, 0x6b, 0x08, 0x7b, 0x1d, 0xf1, 0x0c, 0x0e, 0x6b, 0xc4, 0x8e, 0xbb,
	0x3c, 0x81, 0x7b, 0xef, 0x28, 0x24, 0x4d, 0xdb, 0xd7, 0x79, 0x01, 0x68, 0x96, 0x6d, 0x84, 0x0f,
	0x4c, 0xf8, 0xe2, 0x9f, 0x0d, 0x63, 0x4f, 0xcb, 0x94, 0x7f, 0x23, 0x8f, 0xd2, 0x9f, 0xc2, 0x27,
	0x3c, 0x87, 0xa1, 0xf1, 0x32, 0xf0, 0xb8, 0xf1, 0xe8, 0xe6, 0xc3, 0x9a, 0x9c, 0x6c, 0xc8, 0x96,
	0xe3, 0xcf, 0x61, 0xe8, 0x75, 0xb3, 0xbc, 0xad, 0xac, 0x2e, 0xcf, 0x5f, 0x43, 0xbf, 0xf4, 0x0b,
	0x9d, 0xd6, 0x54, 0x43, 0x97, 0xc9, 0x83, 0x8e, 0xcc, 0x75, 0xff, 0xa9, 0x95, 0x13, 0x4a, 0xf1,
	0x4d, 0x42, 0xdb, 0x52, 0x93, 0xb0, 0xe6, 0xd4, 0xcc, 0xc2, 0x25, 0x40, 0x23, 0x32, 0x3e, 0x6c,
	0x4a, 0x6f, 0x38, 0x34, 0x39, 0xee, 0x4e, 0x5e, 0xa3, 0xbe, 0xde, 0x29, 0x7e, 0x6b, 0xcf, 0xff,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x54, 0xf8, 0xf3, 0x5f, 0xe8, 0x04, 0x00, 0x00,
}
