// Code generated by protoc-gen-go. DO NOT EDIT.
// source: identity.proto

package identity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetIdentityRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIdentityRequest) Reset()         { *m = GetIdentityRequest{} }
func (m *GetIdentityRequest) String() string { return proto.CompactTextString(m) }
func (*GetIdentityRequest) ProtoMessage()    {}
func (*GetIdentityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_2ea0d6755ca8ba04, []int{0}
}
func (m *GetIdentityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIdentityRequest.Unmarshal(m, b)
}
func (m *GetIdentityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIdentityRequest.Marshal(b, m, deterministic)
}
func (dst *GetIdentityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIdentityRequest.Merge(dst, src)
}
func (m *GetIdentityRequest) XXX_Size() int {
	return xxx_messageInfo_GetIdentityRequest.Size(m)
}
func (m *GetIdentityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIdentityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIdentityRequest proto.InternalMessageInfo

func (m *GetIdentityRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetIdentityResponse struct {
	MetadataServer       string   `protobuf:"bytes,1,opt,name=metadata_server,json=metadataServer,proto3" json:"metadata_server,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIdentityResponse) Reset()         { *m = GetIdentityResponse{} }
func (m *GetIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*GetIdentityResponse) ProtoMessage()    {}
func (*GetIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_2ea0d6755ca8ba04, []int{1}
}
func (m *GetIdentityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIdentityResponse.Unmarshal(m, b)
}
func (m *GetIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIdentityResponse.Marshal(b, m, deterministic)
}
func (dst *GetIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIdentityResponse.Merge(dst, src)
}
func (m *GetIdentityResponse) XXX_Size() int {
	return xxx_messageInfo_GetIdentityResponse.Size(m)
}
func (m *GetIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIdentityResponse proto.InternalMessageInfo

func (m *GetIdentityResponse) GetMetadataServer() string {
	if m != nil {
		return m.MetadataServer
	}
	return ""
}

func (m *GetIdentityResponse) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type PutIdentityRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	MetadataServer       string   `protobuf:"bytes,2,opt,name=metadata_server,json=metadataServer,proto3" json:"metadata_server,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutIdentityRequest) Reset()         { *m = PutIdentityRequest{} }
func (m *PutIdentityRequest) String() string { return proto.CompactTextString(m) }
func (*PutIdentityRequest) ProtoMessage()    {}
func (*PutIdentityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_2ea0d6755ca8ba04, []int{2}
}
func (m *PutIdentityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutIdentityRequest.Unmarshal(m, b)
}
func (m *PutIdentityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutIdentityRequest.Marshal(b, m, deterministic)
}
func (dst *PutIdentityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutIdentityRequest.Merge(dst, src)
}
func (m *PutIdentityRequest) XXX_Size() int {
	return xxx_messageInfo_PutIdentityRequest.Size(m)
}
func (m *PutIdentityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutIdentityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutIdentityRequest proto.InternalMessageInfo

func (m *PutIdentityRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PutIdentityRequest) GetMetadataServer() string {
	if m != nil {
		return m.MetadataServer
	}
	return ""
}

func (m *PutIdentityRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type PutIdentityResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutIdentityResponse) Reset()         { *m = PutIdentityResponse{} }
func (m *PutIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*PutIdentityResponse) ProtoMessage()    {}
func (*PutIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_2ea0d6755ca8ba04, []int{3}
}
func (m *PutIdentityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutIdentityResponse.Unmarshal(m, b)
}
func (m *PutIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutIdentityResponse.Marshal(b, m, deterministic)
}
func (dst *PutIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutIdentityResponse.Merge(dst, src)
}
func (m *PutIdentityResponse) XXX_Size() int {
	return xxx_messageInfo_PutIdentityResponse.Size(m)
}
func (m *PutIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutIdentityResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetIdentityRequest)(nil), "identity.GetIdentityRequest")
	proto.RegisterType((*GetIdentityResponse)(nil), "identity.GetIdentityResponse")
	proto.RegisterType((*PutIdentityRequest)(nil), "identity.PutIdentityRequest")
	proto.RegisterType((*PutIdentityResponse)(nil), "identity.PutIdentityResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityServiceClient interface {
	GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*GetIdentityResponse, error)
	PutIdentity(ctx context.Context, in *PutIdentityRequest, opts ...grpc.CallOption) (*PutIdentityResponse, error)
}

type identityServiceClient struct {
	cc *grpc.ClientConn
}

func NewIdentityServiceClient(cc *grpc.ClientConn) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*GetIdentityResponse, error) {
	out := new(GetIdentityResponse)
	err := c.cc.Invoke(ctx, "/identity.IdentityService/GetIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) PutIdentity(ctx context.Context, in *PutIdentityRequest, opts ...grpc.CallOption) (*PutIdentityResponse, error) {
	out := new(PutIdentityResponse)
	err := c.cc.Invoke(ctx, "/identity.IdentityService/PutIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
type IdentityServiceServer interface {
	GetIdentity(context.Context, *GetIdentityRequest) (*GetIdentityResponse, error)
	PutIdentity(context.Context, *PutIdentityRequest) (*PutIdentityResponse, error)
}

func RegisterIdentityServiceServer(s *grpc.Server, srv IdentityServiceServer) {
	s.RegisterService(&_IdentityService_serviceDesc, srv)
}

func _IdentityService_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/identity.IdentityService/GetIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetIdentity(ctx, req.(*GetIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_PutIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).PutIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/identity.IdentityService/PutIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).PutIdentity(ctx, req.(*PutIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdentityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "identity.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIdentity",
			Handler:    _IdentityService_GetIdentity_Handler,
		},
		{
			MethodName: "PutIdentity",
			Handler:    _IdentityService_PutIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity.proto",
}

func init() { proto.RegisterFile("identity.proto", fileDescriptor_identity_2ea0d6755ca8ba04) }

var fileDescriptor_identity_2ea0d6755ca8ba04 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4c, 0x49, 0xcd,
	0x2b, 0xc9, 0x2c, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xb4,
	0xb8, 0x84, 0xdc, 0x53, 0x4b, 0x3c, 0xa1, 0xdc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21,
	0x11, 0x2e, 0xd6, 0xd4, 0xdc, 0xc4, 0xcc, 0x1c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08,
	0x47, 0x29, 0x96, 0x4b, 0x18, 0x45, 0x6d, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x3a, 0x17,
	0x7f, 0x6e, 0x6a, 0x49, 0x62, 0x4a, 0x62, 0x49, 0x62, 0x7c, 0x71, 0x6a, 0x51, 0x59, 0x6a, 0x11,
	0x54, 0x1b, 0x1f, 0x4c, 0x38, 0x18, 0x2c, 0x2a, 0x24, 0xcb, 0xc5, 0x55, 0x50, 0x9a, 0x94, 0x93,
	0x99, 0x1c, 0x9f, 0x9d, 0x5a, 0x29, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x13, 0xc4, 0x09, 0x11, 0xf1,
	0x4e, 0xad, 0x54, 0x2a, 0xe2, 0x12, 0x0a, 0x28, 0x25, 0xce, 0x29, 0xd8, 0xec, 0x64, 0x22, 0xc2,
	0x4e, 0x66, 0x74, 0x3b, 0x45, 0xb9, 0x84, 0x51, 0xec, 0x84, 0x78, 0xc9, 0x68, 0x25, 0x23, 0x17,
	0x3f, 0x4c, 0x10, 0x64, 0x50, 0x66, 0x72, 0xaa, 0x90, 0x17, 0x17, 0x37, 0x92, 0xef, 0x85, 0x64,
	0xf4, 0xe0, 0x61, 0x8a, 0x19, 0x80, 0x52, 0xb2, 0x38, 0x64, 0xa1, 0x41, 0xe6, 0xc5, 0xc5, 0x8d,
	0x64, 0x2d, 0xb2, 0x59, 0x98, 0x21, 0x80, 0x6c, 0x16, 0x16, 0xb7, 0x26, 0xb1, 0x81, 0xa3, 0xd4,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x25, 0xdd, 0xf0, 0xa6, 0xe4, 0x01, 0x00, 0x00,
}
