// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package metadata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TODO (Franz): This should be encrypted; move this to the encryption
// server when its implemented
type Metadata struct {
	Created              *Metadata_UnixTimestamp `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	LastModified         *Metadata_UnixTimestamp `protobuf:"bytes,2,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	Permissions          uint32                  `protobuf:"varint,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Size                 int64                   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	IsDirectory          bool                    `protobuf:"varint,5,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{0}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (dst *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(dst, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetCreated() *Metadata_UnixTimestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Metadata) GetLastModified() *Metadata_UnixTimestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

func (m *Metadata) GetPermissions() uint32 {
	if m != nil {
		return m.Permissions
	}
	return 0
}

func (m *Metadata) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Metadata) GetIsDirectory() bool {
	if m != nil {
		return m.IsDirectory
	}
	return false
}

type Metadata_UnixTimestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanoseconds          int64    `protobuf:"varint,2,opt,name=nanoseconds,proto3" json:"nanoseconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata_UnixTimestamp) Reset()         { *m = Metadata_UnixTimestamp{} }
func (m *Metadata_UnixTimestamp) String() string { return proto.CompactTextString(m) }
func (*Metadata_UnixTimestamp) ProtoMessage()    {}
func (*Metadata_UnixTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{0, 0}
}
func (m *Metadata_UnixTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata_UnixTimestamp.Unmarshal(m, b)
}
func (m *Metadata_UnixTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata_UnixTimestamp.Marshal(b, m, deterministic)
}
func (dst *Metadata_UnixTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata_UnixTimestamp.Merge(dst, src)
}
func (m *Metadata_UnixTimestamp) XXX_Size() int {
	return xxx_messageInfo_Metadata_UnixTimestamp.Size(m)
}
func (m *Metadata_UnixTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata_UnixTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata_UnixTimestamp proto.InternalMessageInfo

func (m *Metadata_UnixTimestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Metadata_UnixTimestamp) GetNanoseconds() int64 {
	if m != nil {
		return m.Nanoseconds
	}
	return 0
}

type GetFileRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileRequest) Reset()         { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()    {}
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{1}
}
func (m *GetFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileRequest.Unmarshal(m, b)
}
func (m *GetFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileRequest.Marshal(b, m, deterministic)
}
func (dst *GetFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileRequest.Merge(dst, src)
}
func (m *GetFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileRequest.Size(m)
}
func (m *GetFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileRequest proto.InternalMessageInfo

func (m *GetFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GetFileResponse struct {
	File                 []byte    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetFileResponse) Reset()         { *m = GetFileResponse{} }
func (m *GetFileResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileResponse) ProtoMessage()    {}
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{2}
}
func (m *GetFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileResponse.Unmarshal(m, b)
}
func (m *GetFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileResponse.Marshal(b, m, deterministic)
}
func (dst *GetFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileResponse.Merge(dst, src)
}
func (m *GetFileResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileResponse.Size(m)
}
func (m *GetFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileResponse proto.InternalMessageInfo

func (m *GetFileResponse) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *GetFileResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type GetFileStreamRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileStreamRequest) Reset()         { *m = GetFileStreamRequest{} }
func (m *GetFileStreamRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileStreamRequest) ProtoMessage()    {}
func (*GetFileStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{3}
}
func (m *GetFileStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileStreamRequest.Unmarshal(m, b)
}
func (m *GetFileStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileStreamRequest.Marshal(b, m, deterministic)
}
func (dst *GetFileStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileStreamRequest.Merge(dst, src)
}
func (m *GetFileStreamRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileStreamRequest.Size(m)
}
func (m *GetFileStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileStreamRequest proto.InternalMessageInfo

func (m *GetFileStreamRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetFileStreamResponse struct {
	FileChunk []byte `protobuf:"bytes,1,opt,name=fileChunk,proto3" json:"fileChunk,omitempty"`
	// Only set on the first message
	Metadata             *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetFileStreamResponse) Reset()         { *m = GetFileStreamResponse{} }
func (m *GetFileStreamResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileStreamResponse) ProtoMessage()    {}
func (*GetFileStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{4}
}
func (m *GetFileStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileStreamResponse.Unmarshal(m, b)
}
func (m *GetFileStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileStreamResponse.Marshal(b, m, deterministic)
}
func (dst *GetFileStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileStreamResponse.Merge(dst, src)
}
func (m *GetFileStreamResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileStreamResponse.Size(m)
}
func (m *GetFileStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileStreamResponse proto.InternalMessageInfo

func (m *GetFileStreamResponse) GetFileChunk() []byte {
	if m != nil {
		return m.FileChunk
	}
	return nil
}

func (m *GetFileStreamResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type PutFileRequest struct {
	Path                 string    `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	File                 []byte    `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PutFileRequest) Reset()         { *m = PutFileRequest{} }
func (m *PutFileRequest) String() string { return proto.CompactTextString(m) }
func (*PutFileRequest) ProtoMessage()    {}
func (*PutFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{5}
}
func (m *PutFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutFileRequest.Unmarshal(m, b)
}
func (m *PutFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutFileRequest.Marshal(b, m, deterministic)
}
func (dst *PutFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutFileRequest.Merge(dst, src)
}
func (m *PutFileRequest) XXX_Size() int {
	return xxx_messageInfo_PutFileRequest.Size(m)
}
func (m *PutFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutFileRequest proto.InternalMessageInfo

func (m *PutFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PutFileRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *PutFileRequest) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type PutFileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutFileResponse) Reset()         { *m = PutFileResponse{} }
func (m *PutFileResponse) String() string { return proto.CompactTextString(m) }
func (*PutFileResponse) ProtoMessage()    {}
func (*PutFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{6}
}
func (m *PutFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutFileResponse.Unmarshal(m, b)
}
func (m *PutFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutFileResponse.Marshal(b, m, deterministic)
}
func (dst *PutFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutFileResponse.Merge(dst, src)
}
func (m *PutFileResponse) XXX_Size() int {
	return xxx_messageInfo_PutFileResponse.Size(m)
}
func (m *PutFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutFileResponse proto.InternalMessageInfo

type PutFileStreamRequest struct {
	// key and metadata should only be set on the first request
	Key                  string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	FileChunk            []byte    `protobuf:"bytes,2,opt,name=fileChunk,proto3" json:"fileChunk,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PutFileStreamRequest) Reset()         { *m = PutFileStreamRequest{} }
func (m *PutFileStreamRequest) String() string { return proto.CompactTextString(m) }
func (*PutFileStreamRequest) ProtoMessage()    {}
func (*PutFileStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{7}
}
func (m *PutFileStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutFileStreamRequest.Unmarshal(m, b)
}
func (m *PutFileStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutFileStreamRequest.Marshal(b, m, deterministic)
}
func (dst *PutFileStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutFileStreamRequest.Merge(dst, src)
}
func (m *PutFileStreamRequest) XXX_Size() int {
	return xxx_messageInfo_PutFileStreamRequest.Size(m)
}
func (m *PutFileStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutFileStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutFileStreamRequest proto.InternalMessageInfo

func (m *PutFileStreamRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutFileStreamRequest) GetFileChunk() []byte {
	if m != nil {
		return m.FileChunk
	}
	return nil
}

func (m *PutFileStreamRequest) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type PutFileStreamResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutFileStreamResponse) Reset()         { *m = PutFileStreamResponse{} }
func (m *PutFileStreamResponse) String() string { return proto.CompactTextString(m) }
func (*PutFileStreamResponse) ProtoMessage()    {}
func (*PutFileStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{8}
}
func (m *PutFileStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutFileStreamResponse.Unmarshal(m, b)
}
func (m *PutFileStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutFileStreamResponse.Marshal(b, m, deterministic)
}
func (dst *PutFileStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutFileStreamResponse.Merge(dst, src)
}
func (m *PutFileStreamResponse) XXX_Size() int {
	return xxx_messageInfo_PutFileStreamResponse.Size(m)
}
func (m *PutFileStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutFileStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutFileStreamResponse proto.InternalMessageInfo

type DeleteFileRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileRequest) Reset()         { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()    {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{9}
}
func (m *DeleteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileRequest.Unmarshal(m, b)
}
func (m *DeleteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileRequest.Merge(dst, src)
}
func (m *DeleteFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileRequest.Size(m)
}
func (m *DeleteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileRequest proto.InternalMessageInfo

func (m *DeleteFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type DeleteFileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileResponse) Reset()         { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()    {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{10}
}
func (m *DeleteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResponse.Unmarshal(m, b)
}
func (m *DeleteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResponse.Merge(dst, src)
}
func (m *DeleteFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResponse.Size(m)
}
func (m *DeleteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResponse proto.InternalMessageInfo

type GetDirectoryEntriesRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDirectoryEntriesRequest) Reset()         { *m = GetDirectoryEntriesRequest{} }
func (m *GetDirectoryEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*GetDirectoryEntriesRequest) ProtoMessage()    {}
func (*GetDirectoryEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{11}
}
func (m *GetDirectoryEntriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDirectoryEntriesRequest.Unmarshal(m, b)
}
func (m *GetDirectoryEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDirectoryEntriesRequest.Marshal(b, m, deterministic)
}
func (dst *GetDirectoryEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDirectoryEntriesRequest.Merge(dst, src)
}
func (m *GetDirectoryEntriesRequest) XXX_Size() int {
	return xxx_messageInfo_GetDirectoryEntriesRequest.Size(m)
}
func (m *GetDirectoryEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDirectoryEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDirectoryEntriesRequest proto.InternalMessageInfo

func (m *GetDirectoryEntriesRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GetDirectoryEntriesResponse struct {
	Entries              []*GetDirectoryEntriesResponse_DirectoryEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *GetDirectoryEntriesResponse) Reset()         { *m = GetDirectoryEntriesResponse{} }
func (m *GetDirectoryEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*GetDirectoryEntriesResponse) ProtoMessage()    {}
func (*GetDirectoryEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{12}
}
func (m *GetDirectoryEntriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDirectoryEntriesResponse.Unmarshal(m, b)
}
func (m *GetDirectoryEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDirectoryEntriesResponse.Marshal(b, m, deterministic)
}
func (dst *GetDirectoryEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDirectoryEntriesResponse.Merge(dst, src)
}
func (m *GetDirectoryEntriesResponse) XXX_Size() int {
	return xxx_messageInfo_GetDirectoryEntriesResponse.Size(m)
}
func (m *GetDirectoryEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDirectoryEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDirectoryEntriesResponse proto.InternalMessageInfo

func (m *GetDirectoryEntriesResponse) GetEntries() []*GetDirectoryEntriesResponse_DirectoryEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type GetDirectoryEntriesResponse_DirectoryEntry struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsDirectory          bool     `protobuf:"varint,2,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDirectoryEntriesResponse_DirectoryEntry) Reset() {
	*m = GetDirectoryEntriesResponse_DirectoryEntry{}
}
func (m *GetDirectoryEntriesResponse_DirectoryEntry) String() string {
	return proto.CompactTextString(m)
}
func (*GetDirectoryEntriesResponse_DirectoryEntry) ProtoMessage() {}
func (*GetDirectoryEntriesResponse_DirectoryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{12, 0}
}
func (m *GetDirectoryEntriesResponse_DirectoryEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDirectoryEntriesResponse_DirectoryEntry.Unmarshal(m, b)
}
func (m *GetDirectoryEntriesResponse_DirectoryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDirectoryEntriesResponse_DirectoryEntry.Marshal(b, m, deterministic)
}
func (dst *GetDirectoryEntriesResponse_DirectoryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDirectoryEntriesResponse_DirectoryEntry.Merge(dst, src)
}
func (m *GetDirectoryEntriesResponse_DirectoryEntry) XXX_Size() int {
	return xxx_messageInfo_GetDirectoryEntriesResponse_DirectoryEntry.Size(m)
}
func (m *GetDirectoryEntriesResponse_DirectoryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDirectoryEntriesResponse_DirectoryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_GetDirectoryEntriesResponse_DirectoryEntry proto.InternalMessageInfo

func (m *GetDirectoryEntriesResponse_DirectoryEntry) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GetDirectoryEntriesResponse_DirectoryEntry) GetIsDirectory() bool {
	if m != nil {
		return m.IsDirectory
	}
	return false
}

type CreateDirectoryRequest struct {
	Path                 string    `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateDirectoryRequest) Reset()         { *m = CreateDirectoryRequest{} }
func (m *CreateDirectoryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDirectoryRequest) ProtoMessage()    {}
func (*CreateDirectoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{13}
}
func (m *CreateDirectoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDirectoryRequest.Unmarshal(m, b)
}
func (m *CreateDirectoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDirectoryRequest.Marshal(b, m, deterministic)
}
func (dst *CreateDirectoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDirectoryRequest.Merge(dst, src)
}
func (m *CreateDirectoryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDirectoryRequest.Size(m)
}
func (m *CreateDirectoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDirectoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDirectoryRequest proto.InternalMessageInfo

func (m *CreateDirectoryRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *CreateDirectoryRequest) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type CreateDirectoryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDirectoryResponse) Reset()         { *m = CreateDirectoryResponse{} }
func (m *CreateDirectoryResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDirectoryResponse) ProtoMessage()    {}
func (*CreateDirectoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{14}
}
func (m *CreateDirectoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDirectoryResponse.Unmarshal(m, b)
}
func (m *CreateDirectoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDirectoryResponse.Marshal(b, m, deterministic)
}
func (dst *CreateDirectoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDirectoryResponse.Merge(dst, src)
}
func (m *CreateDirectoryResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDirectoryResponse.Size(m)
}
func (m *CreateDirectoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDirectoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDirectoryResponse proto.InternalMessageInfo

type DeleteDirectoryRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDirectoryRequest) Reset()         { *m = DeleteDirectoryRequest{} }
func (m *DeleteDirectoryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDirectoryRequest) ProtoMessage()    {}
func (*DeleteDirectoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{15}
}
func (m *DeleteDirectoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDirectoryRequest.Unmarshal(m, b)
}
func (m *DeleteDirectoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDirectoryRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteDirectoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDirectoryRequest.Merge(dst, src)
}
func (m *DeleteDirectoryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDirectoryRequest.Size(m)
}
func (m *DeleteDirectoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDirectoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDirectoryRequest proto.InternalMessageInfo

func (m *DeleteDirectoryRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type DeleteDirectoryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDirectoryResponse) Reset()         { *m = DeleteDirectoryResponse{} }
func (m *DeleteDirectoryResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDirectoryResponse) ProtoMessage()    {}
func (*DeleteDirectoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{16}
}
func (m *DeleteDirectoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDirectoryResponse.Unmarshal(m, b)
}
func (m *DeleteDirectoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDirectoryResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteDirectoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDirectoryResponse.Merge(dst, src)
}
func (m *DeleteDirectoryResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDirectoryResponse.Size(m)
}
func (m *DeleteDirectoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDirectoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDirectoryResponse proto.InternalMessageInfo

type GetMetadataRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMetadataRequest) Reset()         { *m = GetMetadataRequest{} }
func (m *GetMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*GetMetadataRequest) ProtoMessage()    {}
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{17}
}
func (m *GetMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetadataRequest.Unmarshal(m, b)
}
func (m *GetMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetadataRequest.Marshal(b, m, deterministic)
}
func (dst *GetMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetadataRequest.Merge(dst, src)
}
func (m *GetMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_GetMetadataRequest.Size(m)
}
func (m *GetMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetadataRequest proto.InternalMessageInfo

func (m *GetMetadataRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GetMetadataResponse struct {
	Metadata             *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetMetadataResponse) Reset()         { *m = GetMetadataResponse{} }
func (m *GetMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*GetMetadataResponse) ProtoMessage()    {}
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{18}
}
func (m *GetMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetadataResponse.Unmarshal(m, b)
}
func (m *GetMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetadataResponse.Marshal(b, m, deterministic)
}
func (dst *GetMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetadataResponse.Merge(dst, src)
}
func (m *GetMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_GetMetadataResponse.Size(m)
}
func (m *GetMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetadataResponse proto.InternalMessageInfo

func (m *GetMetadataResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SetMetadataRequest struct {
	Path                 string    `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SetMetadataRequest) Reset()         { *m = SetMetadataRequest{} }
func (m *SetMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*SetMetadataRequest) ProtoMessage()    {}
func (*SetMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{19}
}
func (m *SetMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMetadataRequest.Unmarshal(m, b)
}
func (m *SetMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMetadataRequest.Marshal(b, m, deterministic)
}
func (dst *SetMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMetadataRequest.Merge(dst, src)
}
func (m *SetMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_SetMetadataRequest.Size(m)
}
func (m *SetMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetMetadataRequest proto.InternalMessageInfo

func (m *SetMetadataRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SetMetadataRequest) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SetMetadataResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMetadataResponse) Reset()         { *m = SetMetadataResponse{} }
func (m *SetMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*SetMetadataResponse) ProtoMessage()    {}
func (*SetMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9ca051a18058c1bb, []int{20}
}
func (m *SetMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMetadataResponse.Unmarshal(m, b)
}
func (m *SetMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMetadataResponse.Marshal(b, m, deterministic)
}
func (dst *SetMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMetadataResponse.Merge(dst, src)
}
func (m *SetMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_SetMetadataResponse.Size(m)
}
func (m *SetMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetMetadataResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Metadata)(nil), "metadata.Metadata")
	proto.RegisterType((*Metadata_UnixTimestamp)(nil), "metadata.Metadata.UnixTimestamp")
	proto.RegisterType((*GetFileRequest)(nil), "metadata.GetFileRequest")
	proto.RegisterType((*GetFileResponse)(nil), "metadata.GetFileResponse")
	proto.RegisterType((*GetFileStreamRequest)(nil), "metadata.GetFileStreamRequest")
	proto.RegisterType((*GetFileStreamResponse)(nil), "metadata.GetFileStreamResponse")
	proto.RegisterType((*PutFileRequest)(nil), "metadata.PutFileRequest")
	proto.RegisterType((*PutFileResponse)(nil), "metadata.PutFileResponse")
	proto.RegisterType((*PutFileStreamRequest)(nil), "metadata.PutFileStreamRequest")
	proto.RegisterType((*PutFileStreamResponse)(nil), "metadata.PutFileStreamResponse")
	proto.RegisterType((*DeleteFileRequest)(nil), "metadata.DeleteFileRequest")
	proto.RegisterType((*DeleteFileResponse)(nil), "metadata.DeleteFileResponse")
	proto.RegisterType((*GetDirectoryEntriesRequest)(nil), "metadata.GetDirectoryEntriesRequest")
	proto.RegisterType((*GetDirectoryEntriesResponse)(nil), "metadata.GetDirectoryEntriesResponse")
	proto.RegisterType((*GetDirectoryEntriesResponse_DirectoryEntry)(nil), "metadata.GetDirectoryEntriesResponse.DirectoryEntry")
	proto.RegisterType((*CreateDirectoryRequest)(nil), "metadata.CreateDirectoryRequest")
	proto.RegisterType((*CreateDirectoryResponse)(nil), "metadata.CreateDirectoryResponse")
	proto.RegisterType((*DeleteDirectoryRequest)(nil), "metadata.DeleteDirectoryRequest")
	proto.RegisterType((*DeleteDirectoryResponse)(nil), "metadata.DeleteDirectoryResponse")
	proto.RegisterType((*GetMetadataRequest)(nil), "metadata.GetMetadataRequest")
	proto.RegisterType((*GetMetadataResponse)(nil), "metadata.GetMetadataResponse")
	proto.RegisterType((*SetMetadataRequest)(nil), "metadata.SetMetadataRequest")
	proto.RegisterType((*SetMetadataResponse)(nil), "metadata.SetMetadataResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetadataServiceClient interface {
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	GetFileStream(ctx context.Context, in *GetFileStreamRequest, opts ...grpc.CallOption) (MetadataService_GetFileStreamClient, error)
	PutFile(ctx context.Context, in *PutFileRequest, opts ...grpc.CallOption) (*PutFileResponse, error)
	PutFileStream(ctx context.Context, opts ...grpc.CallOption) (MetadataService_PutFileStreamClient, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	CreateDirectory(ctx context.Context, in *CreateDirectoryRequest, opts ...grpc.CallOption) (*CreateDirectoryResponse, error)
	DeleteDirectory(ctx context.Context, in *DeleteDirectoryRequest, opts ...grpc.CallOption) (*DeleteDirectoryResponse, error)
	GetDirectoryEntries(ctx context.Context, in *GetDirectoryEntriesRequest, opts ...grpc.CallOption) (*GetDirectoryEntriesResponse, error)
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error)
	SetMetadata(ctx context.Context, in *SetMetadataRequest, opts ...grpc.CallOption) (*SetMetadataResponse, error)
}

type metadataServiceClient struct {
	cc *grpc.ClientConn
}

func NewMetadataServiceClient(cc *grpc.ClientConn) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/GetFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetFileStream(ctx context.Context, in *GetFileStreamRequest, opts ...grpc.CallOption) (MetadataService_GetFileStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MetadataService_serviceDesc.Streams[0], "/metadata.MetadataService/GetFileStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &metadataServiceGetFileStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MetadataService_GetFileStreamClient interface {
	Recv() (*GetFileStreamResponse, error)
	grpc.ClientStream
}

type metadataServiceGetFileStreamClient struct {
	grpc.ClientStream
}

func (x *metadataServiceGetFileStreamClient) Recv() (*GetFileStreamResponse, error) {
	m := new(GetFileStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *metadataServiceClient) PutFile(ctx context.Context, in *PutFileRequest, opts ...grpc.CallOption) (*PutFileResponse, error) {
	out := new(PutFileResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/PutFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) PutFileStream(ctx context.Context, opts ...grpc.CallOption) (MetadataService_PutFileStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MetadataService_serviceDesc.Streams[1], "/metadata.MetadataService/PutFileStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &metadataServicePutFileStreamClient{stream}
	return x, nil
}

type MetadataService_PutFileStreamClient interface {
	Send(*PutFileStreamRequest) error
	CloseAndRecv() (*PutFileStreamResponse, error)
	grpc.ClientStream
}

type metadataServicePutFileStreamClient struct {
	grpc.ClientStream
}

func (x *metadataServicePutFileStreamClient) Send(m *PutFileStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *metadataServicePutFileStreamClient) CloseAndRecv() (*PutFileStreamResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PutFileStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *metadataServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) CreateDirectory(ctx context.Context, in *CreateDirectoryRequest, opts ...grpc.CallOption) (*CreateDirectoryResponse, error) {
	out := new(CreateDirectoryResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/CreateDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) DeleteDirectory(ctx context.Context, in *DeleteDirectoryRequest, opts ...grpc.CallOption) (*DeleteDirectoryResponse, error) {
	out := new(DeleteDirectoryResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/DeleteDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetDirectoryEntries(ctx context.Context, in *GetDirectoryEntriesRequest, opts ...grpc.CallOption) (*GetDirectoryEntriesResponse, error) {
	out := new(GetDirectoryEntriesResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/GetDirectoryEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error) {
	out := new(GetMetadataResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/GetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) SetMetadata(ctx context.Context, in *SetMetadataRequest, opts ...grpc.CallOption) (*SetMetadataResponse, error) {
	out := new(SetMetadataResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/SetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
type MetadataServiceServer interface {
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	GetFileStream(*GetFileStreamRequest, MetadataService_GetFileStreamServer) error
	PutFile(context.Context, *PutFileRequest) (*PutFileResponse, error)
	PutFileStream(MetadataService_PutFileStreamServer) error
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	CreateDirectory(context.Context, *CreateDirectoryRequest) (*CreateDirectoryResponse, error)
	DeleteDirectory(context.Context, *DeleteDirectoryRequest) (*DeleteDirectoryResponse, error)
	GetDirectoryEntries(context.Context, *GetDirectoryEntriesRequest) (*GetDirectoryEntriesResponse, error)
	GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error)
	SetMetadata(context.Context, *SetMetadataRequest) (*SetMetadataResponse, error)
}

func RegisterMetadataServiceServer(s *grpc.Server, srv MetadataServiceServer) {
	s.RegisterService(&_MetadataService_serviceDesc, srv)
}

func _MetadataService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFileStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetadataServiceServer).GetFileStream(m, &metadataServiceGetFileStreamServer{stream})
}

type MetadataService_GetFileStreamServer interface {
	Send(*GetFileStreamResponse) error
	grpc.ServerStream
}

type metadataServiceGetFileStreamServer struct {
	grpc.ServerStream
}

func (x *metadataServiceGetFileStreamServer) Send(m *GetFileStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _MetadataService_PutFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).PutFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/PutFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).PutFile(ctx, req.(*PutFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_PutFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetadataServiceServer).PutFileStream(&metadataServicePutFileStreamServer{stream})
}

type MetadataService_PutFileStreamServer interface {
	SendAndClose(*PutFileStreamResponse) error
	Recv() (*PutFileStreamRequest, error)
	grpc.ServerStream
}

type metadataServicePutFileStreamServer struct {
	grpc.ServerStream
}

func (x *metadataServicePutFileStreamServer) SendAndClose(m *PutFileStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *metadataServicePutFileStreamServer) Recv() (*PutFileStreamRequest, error) {
	m := new(PutFileStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MetadataService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_CreateDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CreateDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/CreateDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CreateDirectory(ctx, req.(*CreateDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_DeleteDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).DeleteDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/DeleteDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).DeleteDirectory(ctx, req.(*DeleteDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetDirectoryEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirectoryEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetDirectoryEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/GetDirectoryEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetDirectoryEntries(ctx, req.(*GetDirectoryEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/GetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_SetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).SetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/SetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).SetMetadata(ctx, req.(*SetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetadataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metadata.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFile",
			Handler:    _MetadataService_GetFile_Handler,
		},
		{
			MethodName: "PutFile",
			Handler:    _MetadataService_PutFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _MetadataService_DeleteFile_Handler,
		},
		{
			MethodName: "CreateDirectory",
			Handler:    _MetadataService_CreateDirectory_Handler,
		},
		{
			MethodName: "DeleteDirectory",
			Handler:    _MetadataService_DeleteDirectory_Handler,
		},
		{
			MethodName: "GetDirectoryEntries",
			Handler:    _MetadataService_GetDirectoryEntries_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _MetadataService_GetMetadata_Handler,
		},
		{
			MethodName: "SetMetadata",
			Handler:    _MetadataService_SetMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFileStream",
			Handler:       _MetadataService_GetFileStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PutFileStream",
			Handler:       _MetadataService_PutFileStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "metadata.proto",
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_metadata_9ca051a18058c1bb) }

var fileDescriptor_metadata_9ca051a18058c1bb = []byte{
	// 687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0x96, 0x93, 0xd2, 0xb4, 0x93, 0x26, 0xa1, 0xdb, 0x97, 0xeb, 0x16, 0x70, 0xad, 0x22, 0x7c,
	0x40, 0x51, 0x55, 0x38, 0x71, 0xe0, 0xd2, 0x96, 0x48, 0xa0, 0x22, 0x64, 0x53, 0xc4, 0x01, 0xa9,
	0x72, 0xe3, 0xa9, 0xba, 0x6a, 0x6c, 0x07, 0xef, 0xb6, 0xa2, 0xfc, 0x28, 0x2e, 0x48, 0xfc, 0x3e,
	0x64, 0x67, 0x6d, 0xaf, 0x1f, 0x71, 0xdc, 0xdb, 0x7a, 0x1e, 0xdf, 0x7c, 0xb3, 0x3b, 0xdf, 0x24,
	0xd0, 0xf7, 0x90, 0x3b, 0xae, 0xc3, 0x9d, 0xe1, 0x34, 0x0c, 0x78, 0x40, 0x56, 0x92, 0x6f, 0xe3,
	0x6f, 0x0b, 0x56, 0xce, 0xc5, 0x07, 0x79, 0x07, 0x9d, 0x71, 0x88, 0x0e, 0x47, 0x57, 0x55, 0x74,
	0xc5, 0xec, 0x1e, 0xeb, 0xc3, 0x34, 0x31, 0x09, 0x1a, 0x5e, 0xf8, 0xf4, 0xd7, 0x57, 0xea, 0x21,
	0xe3, 0x8e, 0x37, 0xb5, 0x92, 0x04, 0x72, 0x06, 0xbd, 0x89, 0xc3, 0xf8, 0xa5, 0x17, 0xb8, 0xf4,
	0x9a, 0xa2, 0xab, 0xb6, 0x1a, 0x22, 0xac, 0x45, 0x69, 0xe7, 0x22, 0x8b, 0xe8, 0xd0, 0x9d, 0x62,
	0xe8, 0x51, 0xc6, 0x68, 0xe0, 0x33, 0xb5, 0xad, 0x2b, 0x66, 0xcf, 0x92, 0x4d, 0x84, 0xc0, 0x12,
	0xa3, 0xbf, 0x51, 0x5d, 0xd2, 0x15, 0xb3, 0x6d, 0xc5, 0x67, 0x72, 0x00, 0x6b, 0x94, 0x5d, 0xba,
	0x34, 0xc4, 0x31, 0x0f, 0xc2, 0x07, 0xf5, 0x89, 0xae, 0x98, 0x2b, 0x56, 0x97, 0xb2, 0xd3, 0xc4,
	0xa4, 0x7d, 0x82, 0x5e, 0xae, 0x2e, 0x51, 0xa1, 0xc3, 0x70, 0x1c, 0xf8, 0x2e, 0x8b, 0x9b, 0x6d,
	0x5b, 0xc9, 0x67, 0xc4, 0xc1, 0x77, 0xfc, 0x20, 0xf1, 0xb6, 0x62, 0xaf, 0x6c, 0x32, 0x0e, 0xa1,
	0x3f, 0x42, 0xfe, 0x81, 0x4e, 0xd0, 0xc2, 0x9f, 0x77, 0xc8, 0x78, 0xc4, 0x6a, 0xea, 0xf0, 0x9b,
	0x18, 0x6a, 0xd5, 0x8a, 0xcf, 0xc6, 0x05, 0x0c, 0xd2, 0x28, 0x36, 0x0d, 0x7c, 0x86, 0x51, 0xd8,
	0x35, 0x9d, 0x60, 0x1c, 0xb6, 0x66, 0xc5, 0x67, 0x32, 0x84, 0xf4, 0x39, 0xc4, 0xa5, 0x91, 0xf2,
	0xa5, 0x59, 0xd9, 0x93, 0x99, 0xb0, 0x29, 0x60, 0x6d, 0x1e, 0xa2, 0xe3, 0x25, 0x14, 0x9e, 0x42,
	0xfb, 0x16, 0x1f, 0x04, 0x83, 0xe8, 0x68, 0x20, 0x6c, 0x15, 0x22, 0x05, 0x8d, 0x7d, 0x58, 0x8d,
	0x4a, 0x9f, 0xdc, 0xdc, 0xf9, 0xb7, 0x82, 0x4b, 0x66, 0x78, 0x34, 0xa1, 0x1b, 0xe8, 0x7f, 0xb9,
	0x5b, 0x74, 0x1b, 0x69, 0xeb, 0xad, 0x39, 0xad, 0xb7, 0x1b, 0x54, 0x5a, 0x87, 0x41, 0x5a, 0x69,
	0xd6, 0x8a, 0x71, 0x0f, 0x9b, 0xc2, 0xb4, 0xe0, 0x36, 0xf2, 0x4d, 0xb7, 0xea, 0x9a, 0x6e, 0x42,
	0x65, 0x07, 0xb6, 0x0a, 0x75, 0x05, 0xa1, 0x57, 0xb0, 0x7e, 0x8a, 0x13, 0xe4, 0xb8, 0x68, 0x3c,
	0x36, 0x81, 0xc8, 0x81, 0x22, 0xfd, 0x08, 0xb4, 0x11, 0xf2, 0x74, 0x6e, 0xcf, 0x7c, 0x1e, 0x52,
	0x64, 0x75, 0x38, 0xff, 0x14, 0xd8, 0xab, 0x4c, 0x11, 0x8f, 0xfd, 0x19, 0x3a, 0x38, 0x33, 0xa9,
	0x8a, 0xde, 0x36, 0xbb, 0xc7, 0x6f, 0xb3, 0xc6, 0x6a, 0xf2, 0x86, 0x39, 0xc7, 0x83, 0x95, 0x80,
	0x68, 0x23, 0xe8, 0xe7, 0x5d, 0x95, 0xcf, 0x5d, 0x94, 0x64, 0xab, 0x24, 0x49, 0xe3, 0x07, 0x6c,
	0x9f, 0xc4, 0xdb, 0x23, 0x35, 0xd5, 0xcd, 0xcf, 0x63, 0xa7, 0x72, 0x17, 0x76, 0x4a, 0xe8, 0xe2,
	0x8e, 0x5f, 0xc3, 0xf6, 0xec, 0xe6, 0x9b, 0x14, 0x8e, 0x80, 0x4a, 0xd1, 0x02, 0xc8, 0x04, 0x32,
	0x42, 0x9e, 0x16, 0xaf, 0x01, 0x39, 0x83, 0x8d, 0x5c, 0xa4, 0x78, 0x1b, 0xb9, 0x29, 0xa5, 0x41,
	0x53, 0xdf, 0x81, 0xd8, 0x8d, 0x0a, 0x3e, 0xfa, 0xba, 0xb6, 0x60, 0xc3, 0x2e, 0x13, 0x3c, 0xfe,
	0xb3, 0x0c, 0x83, 0xc4, 0x68, 0x63, 0x78, 0x4f, 0xc7, 0x48, 0xde, 0x43, 0x47, 0xac, 0x15, 0xa2,
	0xe6, 0x46, 0x49, 0x9a, 0x78, 0x6d, 0xb7, 0xc2, 0x23, 0x9a, 0xb6, 0xa0, 0x97, 0x5b, 0x4b, 0xe4,
	0x79, 0x29, 0x36, 0xa7, 0x65, 0xed, 0xc5, 0x5c, 0xff, 0x0c, 0xf1, 0x48, 0x89, 0x38, 0x09, 0x39,
	0xca, 0x9c, 0xf2, 0x6b, 0x49, 0xe6, 0x54, 0x58, 0x23, 0x11, 0xa7, 0x9c, 0x9c, 0x65, 0x4e, 0x55,
	0xfb, 0x45, 0xe6, 0x54, 0xb9, 0x07, 0x4c, 0x85, 0x8c, 0x00, 0x32, 0x81, 0x93, 0xbd, 0x2c, 0xa1,
	0xb4, 0x1f, 0xb4, 0xfd, 0x6a, 0xa7, 0x20, 0xf7, 0x0d, 0x06, 0x85, 0x51, 0x26, 0xd2, 0xef, 0x6a,
	0xb5, 0x86, 0xb4, 0x83, 0x9a, 0x88, 0x0c, 0xb7, 0x30, 0xd9, 0x32, 0x6e, 0xb5, 0x44, 0x64, 0xdc,
	0x39, 0xb2, 0x20, 0x57, 0xf1, 0xb0, 0x17, 0x17, 0x0b, 0x39, 0x5c, 0xb0, 0x77, 0x66, 0xf8, 0x2f,
	0x1b, 0x6d, 0x27, 0xf2, 0x11, 0xba, 0x92, 0xa0, 0xc8, 0x7e, 0x2e, 0xab, 0x20, 0x10, 0xed, 0xd9,
	0x1c, 0x6f, 0x86, 0x65, 0x57, 0x63, 0xd9, 0xb5, 0x58, 0x15, 0x82, 0xb9, 0x5a, 0x8e, 0xff, 0x61,
	0xbd, 0xf9, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xee, 0xe5, 0x1f, 0x91, 0x73, 0x09, 0x00, 0x00,
}
