// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package metadata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TODO (Franz): This should be encrypted; move this to the encryption
// server when its implemented
type FileMetadata struct {
	Created              *FileMetadata_UnixTimestamp `protobuf:"bytes,1,opt,name=created" json:"created,omitempty"`
	LastModified         *FileMetadata_UnixTimestamp `protobuf:"bytes,2,opt,name=last_modified,json=lastModified" json:"last_modified,omitempty"`
	Permissions          uint32                      `protobuf:"varint,3,opt,name=permissions" json:"permissions,omitempty"`
	Size                 int64                       `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	IsDirectory          bool                        `protobuf:"varint,5,opt,name=is_directory,json=isDirectory" json:"is_directory,omitempty"`
	ParentDirectory      string                      `protobuf:"bytes,6,opt,name=parent_directory,json=parentDirectory" json:"parent_directory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *FileMetadata) Reset()         { *m = FileMetadata{} }
func (m *FileMetadata) String() string { return proto.CompactTextString(m) }
func (*FileMetadata) ProtoMessage()    {}
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{0}
}
func (m *FileMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMetadata.Unmarshal(m, b)
}
func (m *FileMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMetadata.Marshal(b, m, deterministic)
}
func (dst *FileMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMetadata.Merge(dst, src)
}
func (m *FileMetadata) XXX_Size() int {
	return xxx_messageInfo_FileMetadata.Size(m)
}
func (m *FileMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_FileMetadata proto.InternalMessageInfo

func (m *FileMetadata) GetCreated() *FileMetadata_UnixTimestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *FileMetadata) GetLastModified() *FileMetadata_UnixTimestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

func (m *FileMetadata) GetPermissions() uint32 {
	if m != nil {
		return m.Permissions
	}
	return 0
}

func (m *FileMetadata) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileMetadata) GetIsDirectory() bool {
	if m != nil {
		return m.IsDirectory
	}
	return false
}

func (m *FileMetadata) GetParentDirectory() string {
	if m != nil {
		return m.ParentDirectory
	}
	return ""
}

type FileMetadata_UnixTimestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	Nanoseconds          int64    `protobuf:"varint,2,opt,name=nanoseconds" json:"nanoseconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileMetadata_UnixTimestamp) Reset()         { *m = FileMetadata_UnixTimestamp{} }
func (m *FileMetadata_UnixTimestamp) String() string { return proto.CompactTextString(m) }
func (*FileMetadata_UnixTimestamp) ProtoMessage()    {}
func (*FileMetadata_UnixTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{0, 0}
}
func (m *FileMetadata_UnixTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMetadata_UnixTimestamp.Unmarshal(m, b)
}
func (m *FileMetadata_UnixTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMetadata_UnixTimestamp.Marshal(b, m, deterministic)
}
func (dst *FileMetadata_UnixTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMetadata_UnixTimestamp.Merge(dst, src)
}
func (m *FileMetadata_UnixTimestamp) XXX_Size() int {
	return xxx_messageInfo_FileMetadata_UnixTimestamp.Size(m)
}
func (m *FileMetadata_UnixTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMetadata_UnixTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_FileMetadata_UnixTimestamp proto.InternalMessageInfo

func (m *FileMetadata_UnixTimestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *FileMetadata_UnixTimestamp) GetNanoseconds() int64 {
	if m != nil {
		return m.Nanoseconds
	}
	return 0
}

type DirEntry struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	IsDirectory          bool     `protobuf:"varint,2,opt,name=is_directory,json=isDirectory" json:"is_directory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirEntry) Reset()         { *m = DirEntry{} }
func (m *DirEntry) String() string { return proto.CompactTextString(m) }
func (*DirEntry) ProtoMessage()    {}
func (*DirEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{1}
}
func (m *DirEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirEntry.Unmarshal(m, b)
}
func (m *DirEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirEntry.Marshal(b, m, deterministic)
}
func (dst *DirEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirEntry.Merge(dst, src)
}
func (m *DirEntry) XXX_Size() int {
	return xxx_messageInfo_DirEntry.Size(m)
}
func (m *DirEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DirEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DirEntry proto.InternalMessageInfo

func (m *DirEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DirEntry) GetIsDirectory() bool {
	if m != nil {
		return m.IsDirectory
	}
	return false
}

type GetDirectoryKeysRequest struct {
	Directory            string   `protobuf:"bytes,1,opt,name=directory" json:"directory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDirectoryKeysRequest) Reset()         { *m = GetDirectoryKeysRequest{} }
func (m *GetDirectoryKeysRequest) String() string { return proto.CompactTextString(m) }
func (*GetDirectoryKeysRequest) ProtoMessage()    {}
func (*GetDirectoryKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{2}
}
func (m *GetDirectoryKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDirectoryKeysRequest.Unmarshal(m, b)
}
func (m *GetDirectoryKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDirectoryKeysRequest.Marshal(b, m, deterministic)
}
func (dst *GetDirectoryKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDirectoryKeysRequest.Merge(dst, src)
}
func (m *GetDirectoryKeysRequest) XXX_Size() int {
	return xxx_messageInfo_GetDirectoryKeysRequest.Size(m)
}
func (m *GetDirectoryKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDirectoryKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDirectoryKeysRequest proto.InternalMessageInfo

func (m *GetDirectoryKeysRequest) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

type GetDirectoryKeysResponse struct {
	Entries              []*DirEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetDirectoryKeysResponse) Reset()         { *m = GetDirectoryKeysResponse{} }
func (m *GetDirectoryKeysResponse) String() string { return proto.CompactTextString(m) }
func (*GetDirectoryKeysResponse) ProtoMessage()    {}
func (*GetDirectoryKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{3}
}
func (m *GetDirectoryKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDirectoryKeysResponse.Unmarshal(m, b)
}
func (m *GetDirectoryKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDirectoryKeysResponse.Marshal(b, m, deterministic)
}
func (dst *GetDirectoryKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDirectoryKeysResponse.Merge(dst, src)
}
func (m *GetDirectoryKeysResponse) XXX_Size() int {
	return xxx_messageInfo_GetDirectoryKeysResponse.Size(m)
}
func (m *GetDirectoryKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDirectoryKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDirectoryKeysResponse proto.InternalMessageInfo

func (m *GetDirectoryKeysResponse) GetEntries() []*DirEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type GetMetadataRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMetadataRequest) Reset()         { *m = GetMetadataRequest{} }
func (m *GetMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*GetMetadataRequest) ProtoMessage()    {}
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{4}
}
func (m *GetMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetadataRequest.Unmarshal(m, b)
}
func (m *GetMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetadataRequest.Marshal(b, m, deterministic)
}
func (dst *GetMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetadataRequest.Merge(dst, src)
}
func (m *GetMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_GetMetadataRequest.Size(m)
}
func (m *GetMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetadataRequest proto.InternalMessageInfo

func (m *GetMetadataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetMetadataResponse struct {
	Metadata             *FileMetadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetMetadataResponse) Reset()         { *m = GetMetadataResponse{} }
func (m *GetMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*GetMetadataResponse) ProtoMessage()    {}
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{5}
}
func (m *GetMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetadataResponse.Unmarshal(m, b)
}
func (m *GetMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetadataResponse.Marshal(b, m, deterministic)
}
func (dst *GetMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetadataResponse.Merge(dst, src)
}
func (m *GetMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_GetMetadataResponse.Size(m)
}
func (m *GetMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetadataResponse proto.InternalMessageInfo

func (m *GetMetadataResponse) GetMetadata() *FileMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SetMetadataRequest struct {
	Key                  string        `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Metadata             *FileMetadata `protobuf:"bytes,2,opt,name=metadata" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SetMetadataRequest) Reset()         { *m = SetMetadataRequest{} }
func (m *SetMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*SetMetadataRequest) ProtoMessage()    {}
func (*SetMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{6}
}
func (m *SetMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMetadataRequest.Unmarshal(m, b)
}
func (m *SetMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMetadataRequest.Marshal(b, m, deterministic)
}
func (dst *SetMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMetadataRequest.Merge(dst, src)
}
func (m *SetMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_SetMetadataRequest.Size(m)
}
func (m *SetMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetMetadataRequest proto.InternalMessageInfo

func (m *SetMetadataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetMetadataRequest) GetMetadata() *FileMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SetMetadataResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMetadataResponse) Reset()         { *m = SetMetadataResponse{} }
func (m *SetMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*SetMetadataResponse) ProtoMessage()    {}
func (*SetMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{7}
}
func (m *SetMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMetadataResponse.Unmarshal(m, b)
}
func (m *SetMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMetadataResponse.Marshal(b, m, deterministic)
}
func (dst *SetMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMetadataResponse.Merge(dst, src)
}
func (m *SetMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_SetMetadataResponse.Size(m)
}
func (m *SetMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetMetadataResponse proto.InternalMessageInfo

type GetFileRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileRequest) Reset()         { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()    {}
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{8}
}
func (m *GetFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileRequest.Unmarshal(m, b)
}
func (m *GetFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileRequest.Marshal(b, m, deterministic)
}
func (dst *GetFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileRequest.Merge(dst, src)
}
func (m *GetFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileRequest.Size(m)
}
func (m *GetFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileRequest proto.InternalMessageInfo

func (m *GetFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetFileResponse struct {
	File                 []byte        `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Metadata             *FileMetadata `protobuf:"bytes,2,opt,name=metadata" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetFileResponse) Reset()         { *m = GetFileResponse{} }
func (m *GetFileResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileResponse) ProtoMessage()    {}
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{9}
}
func (m *GetFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileResponse.Unmarshal(m, b)
}
func (m *GetFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileResponse.Marshal(b, m, deterministic)
}
func (dst *GetFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileResponse.Merge(dst, src)
}
func (m *GetFileResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileResponse.Size(m)
}
func (m *GetFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileResponse proto.InternalMessageInfo

func (m *GetFileResponse) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *GetFileResponse) GetMetadata() *FileMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type PutFileRequest struct {
	Key                  string        `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	File                 []byte        `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Metadata             *FileMetadata `protobuf:"bytes,3,opt,name=metadata" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PutFileRequest) Reset()         { *m = PutFileRequest{} }
func (m *PutFileRequest) String() string { return proto.CompactTextString(m) }
func (*PutFileRequest) ProtoMessage()    {}
func (*PutFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{10}
}
func (m *PutFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutFileRequest.Unmarshal(m, b)
}
func (m *PutFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutFileRequest.Marshal(b, m, deterministic)
}
func (dst *PutFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutFileRequest.Merge(dst, src)
}
func (m *PutFileRequest) XXX_Size() int {
	return xxx_messageInfo_PutFileRequest.Size(m)
}
func (m *PutFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutFileRequest proto.InternalMessageInfo

func (m *PutFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutFileRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *PutFileRequest) GetMetadata() *FileMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type PutFileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutFileResponse) Reset()         { *m = PutFileResponse{} }
func (m *PutFileResponse) String() string { return proto.CompactTextString(m) }
func (*PutFileResponse) ProtoMessage()    {}
func (*PutFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{11}
}
func (m *PutFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutFileResponse.Unmarshal(m, b)
}
func (m *PutFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutFileResponse.Marshal(b, m, deterministic)
}
func (dst *PutFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutFileResponse.Merge(dst, src)
}
func (m *PutFileResponse) XXX_Size() int {
	return xxx_messageInfo_PutFileResponse.Size(m)
}
func (m *PutFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutFileResponse proto.InternalMessageInfo

type DeleteFileRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileRequest) Reset()         { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()    {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{12}
}
func (m *DeleteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileRequest.Unmarshal(m, b)
}
func (m *DeleteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileRequest.Merge(dst, src)
}
func (m *DeleteFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileRequest.Size(m)
}
func (m *DeleteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileRequest proto.InternalMessageInfo

func (m *DeleteFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteFileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileResponse) Reset()         { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()    {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{13}
}
func (m *DeleteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResponse.Unmarshal(m, b)
}
func (m *DeleteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResponse.Merge(dst, src)
}
func (m *DeleteFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResponse.Size(m)
}
func (m *DeleteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResponse proto.InternalMessageInfo

type CreateDirectoryRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDirectoryRequest) Reset()         { *m = CreateDirectoryRequest{} }
func (m *CreateDirectoryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDirectoryRequest) ProtoMessage()    {}
func (*CreateDirectoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{14}
}
func (m *CreateDirectoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDirectoryRequest.Unmarshal(m, b)
}
func (m *CreateDirectoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDirectoryRequest.Marshal(b, m, deterministic)
}
func (dst *CreateDirectoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDirectoryRequest.Merge(dst, src)
}
func (m *CreateDirectoryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDirectoryRequest.Size(m)
}
func (m *CreateDirectoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDirectoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDirectoryRequest proto.InternalMessageInfo

func (m *CreateDirectoryRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type CreateDirectoryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDirectoryResponse) Reset()         { *m = CreateDirectoryResponse{} }
func (m *CreateDirectoryResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDirectoryResponse) ProtoMessage()    {}
func (*CreateDirectoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{15}
}
func (m *CreateDirectoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDirectoryResponse.Unmarshal(m, b)
}
func (m *CreateDirectoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDirectoryResponse.Marshal(b, m, deterministic)
}
func (dst *CreateDirectoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDirectoryResponse.Merge(dst, src)
}
func (m *CreateDirectoryResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDirectoryResponse.Size(m)
}
func (m *CreateDirectoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDirectoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDirectoryResponse proto.InternalMessageInfo

type DeleteDirectoryRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDirectoryRequest) Reset()         { *m = DeleteDirectoryRequest{} }
func (m *DeleteDirectoryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDirectoryRequest) ProtoMessage()    {}
func (*DeleteDirectoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{16}
}
func (m *DeleteDirectoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDirectoryRequest.Unmarshal(m, b)
}
func (m *DeleteDirectoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDirectoryRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteDirectoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDirectoryRequest.Merge(dst, src)
}
func (m *DeleteDirectoryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDirectoryRequest.Size(m)
}
func (m *DeleteDirectoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDirectoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDirectoryRequest proto.InternalMessageInfo

func (m *DeleteDirectoryRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteDirectoryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDirectoryResponse) Reset()         { *m = DeleteDirectoryResponse{} }
func (m *DeleteDirectoryResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDirectoryResponse) ProtoMessage()    {}
func (*DeleteDirectoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_9fdba1e98eda1ced, []int{17}
}
func (m *DeleteDirectoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDirectoryResponse.Unmarshal(m, b)
}
func (m *DeleteDirectoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDirectoryResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteDirectoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDirectoryResponse.Merge(dst, src)
}
func (m *DeleteDirectoryResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDirectoryResponse.Size(m)
}
func (m *DeleteDirectoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDirectoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDirectoryResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FileMetadata)(nil), "metadata.FileMetadata")
	proto.RegisterType((*FileMetadata_UnixTimestamp)(nil), "metadata.FileMetadata.UnixTimestamp")
	proto.RegisterType((*DirEntry)(nil), "metadata.DirEntry")
	proto.RegisterType((*GetDirectoryKeysRequest)(nil), "metadata.GetDirectoryKeysRequest")
	proto.RegisterType((*GetDirectoryKeysResponse)(nil), "metadata.GetDirectoryKeysResponse")
	proto.RegisterType((*GetMetadataRequest)(nil), "metadata.GetMetadataRequest")
	proto.RegisterType((*GetMetadataResponse)(nil), "metadata.GetMetadataResponse")
	proto.RegisterType((*SetMetadataRequest)(nil), "metadata.SetMetadataRequest")
	proto.RegisterType((*SetMetadataResponse)(nil), "metadata.SetMetadataResponse")
	proto.RegisterType((*GetFileRequest)(nil), "metadata.GetFileRequest")
	proto.RegisterType((*GetFileResponse)(nil), "metadata.GetFileResponse")
	proto.RegisterType((*PutFileRequest)(nil), "metadata.PutFileRequest")
	proto.RegisterType((*PutFileResponse)(nil), "metadata.PutFileResponse")
	proto.RegisterType((*DeleteFileRequest)(nil), "metadata.DeleteFileRequest")
	proto.RegisterType((*DeleteFileResponse)(nil), "metadata.DeleteFileResponse")
	proto.RegisterType((*CreateDirectoryRequest)(nil), "metadata.CreateDirectoryRequest")
	proto.RegisterType((*CreateDirectoryResponse)(nil), "metadata.CreateDirectoryResponse")
	proto.RegisterType((*DeleteDirectoryRequest)(nil), "metadata.DeleteDirectoryRequest")
	proto.RegisterType((*DeleteDirectoryResponse)(nil), "metadata.DeleteDirectoryResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetadataServiceClient interface {
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	PutFile(ctx context.Context, in *PutFileRequest, opts ...grpc.CallOption) (*PutFileResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error)
	SetMetadata(ctx context.Context, in *SetMetadataRequest, opts ...grpc.CallOption) (*SetMetadataResponse, error)
	GetDirectoryKeys(ctx context.Context, in *GetDirectoryKeysRequest, opts ...grpc.CallOption) (*GetDirectoryKeysResponse, error)
	CreateDirectory(ctx context.Context, in *CreateDirectoryRequest, opts ...grpc.CallOption) (*CreateDirectoryResponse, error)
	DeleteDirectory(ctx context.Context, in *DeleteDirectoryRequest, opts ...grpc.CallOption) (*DeleteDirectoryResponse, error)
}

type metadataServiceClient struct {
	cc *grpc.ClientConn
}

func NewMetadataServiceClient(cc *grpc.ClientConn) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/GetFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) PutFile(ctx context.Context, in *PutFileRequest, opts ...grpc.CallOption) (*PutFileResponse, error) {
	out := new(PutFileResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/PutFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error) {
	out := new(GetMetadataResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/GetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) SetMetadata(ctx context.Context, in *SetMetadataRequest, opts ...grpc.CallOption) (*SetMetadataResponse, error) {
	out := new(SetMetadataResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/SetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetDirectoryKeys(ctx context.Context, in *GetDirectoryKeysRequest, opts ...grpc.CallOption) (*GetDirectoryKeysResponse, error) {
	out := new(GetDirectoryKeysResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/GetDirectoryKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) CreateDirectory(ctx context.Context, in *CreateDirectoryRequest, opts ...grpc.CallOption) (*CreateDirectoryResponse, error) {
	out := new(CreateDirectoryResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/CreateDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) DeleteDirectory(ctx context.Context, in *DeleteDirectoryRequest, opts ...grpc.CallOption) (*DeleteDirectoryResponse, error) {
	out := new(DeleteDirectoryResponse)
	err := c.cc.Invoke(ctx, "/metadata.MetadataService/DeleteDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
type MetadataServiceServer interface {
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	PutFile(context.Context, *PutFileRequest) (*PutFileResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error)
	SetMetadata(context.Context, *SetMetadataRequest) (*SetMetadataResponse, error)
	GetDirectoryKeys(context.Context, *GetDirectoryKeysRequest) (*GetDirectoryKeysResponse, error)
	CreateDirectory(context.Context, *CreateDirectoryRequest) (*CreateDirectoryResponse, error)
	DeleteDirectory(context.Context, *DeleteDirectoryRequest) (*DeleteDirectoryResponse, error)
}

func RegisterMetadataServiceServer(s *grpc.Server, srv MetadataServiceServer) {
	s.RegisterService(&_MetadataService_serviceDesc, srv)
}

func _MetadataService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_PutFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).PutFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/PutFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).PutFile(ctx, req.(*PutFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/GetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_SetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).SetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/SetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).SetMetadata(ctx, req.(*SetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetDirectoryKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirectoryKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetDirectoryKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/GetDirectoryKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetDirectoryKeys(ctx, req.(*GetDirectoryKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_CreateDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CreateDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/CreateDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CreateDirectory(ctx, req.(*CreateDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_DeleteDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).DeleteDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.MetadataService/DeleteDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).DeleteDirectory(ctx, req.(*DeleteDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetadataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metadata.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFile",
			Handler:    _MetadataService_GetFile_Handler,
		},
		{
			MethodName: "PutFile",
			Handler:    _MetadataService_PutFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _MetadataService_DeleteFile_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _MetadataService_GetMetadata_Handler,
		},
		{
			MethodName: "SetMetadata",
			Handler:    _MetadataService_SetMetadata_Handler,
		},
		{
			MethodName: "GetDirectoryKeys",
			Handler:    _MetadataService_GetDirectoryKeys_Handler,
		},
		{
			MethodName: "CreateDirectory",
			Handler:    _MetadataService_CreateDirectory_Handler,
		},
		{
			MethodName: "DeleteDirectory",
			Handler:    _MetadataService_DeleteDirectory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metadata.proto",
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_metadata_9fdba1e98eda1ced) }

var fileDescriptor_metadata_9fdba1e98eda1ced = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xed, 0xd0, 0xb4, 0x93, 0xb4, 0x69, 0xa7, 0xd0, 0xba, 0xa6, 0x48, 0x8e, 0x05, 0xc8,
	0x20, 0x94, 0x43, 0x38, 0x70, 0xab, 0x84, 0x08, 0x84, 0x52, 0x55, 0x42, 0x0e, 0x20, 0x95, 0x4b,
	0x65, 0xe2, 0xa9, 0xb4, 0x10, 0xdb, 0xc1, 0xbb, 0x45, 0x84, 0x9f, 0xcc, 0x7f, 0x40, 0x42, 0x76,
	0xd6, 0xdf, 0x4e, 0x14, 0xb8, 0xad, 0x67, 0xdf, 0x7b, 0x33, 0x3b, 0xf3, 0x76, 0x0d, 0x7b, 0x3e,
	0x09, 0xd7, 0x73, 0x85, 0x3b, 0x98, 0x47, 0xa1, 0x08, 0x71, 0x3b, 0xfd, 0xb6, 0x7e, 0xab, 0xd0,
	0x7d, 0xc3, 0x66, 0x74, 0x29, 0x03, 0x78, 0x06, 0xed, 0x69, 0x44, 0xae, 0x20, 0x4f, 0x57, 0x4c,
	0xc5, 0xee, 0x0c, 0x1f, 0x0e, 0x32, 0x72, 0x11, 0x38, 0xf8, 0x18, 0xb0, 0x9f, 0x1f, 0x98, 0x4f,
	0x5c, 0xb8, 0xfe, 0xdc, 0x49, 0x49, 0x78, 0x0e, 0xbb, 0x33, 0x97, 0x8b, 0x6b, 0x3f, 0xf4, 0xd8,
	0x0d, 0x23, 0x4f, 0x57, 0xff, 0x41, 0xa5, 0x1b, 0x53, 0x2f, 0x25, 0x13, 0x4d, 0xe8, 0xcc, 0x29,
	0xf2, 0x19, 0xe7, 0x2c, 0x0c, 0xb8, 0xae, 0x99, 0x8a, 0xbd, 0xeb, 0x14, 0x43, 0x88, 0xd0, 0xe2,
	0xec, 0x17, 0xe9, 0x2d, 0x53, 0xb1, 0x35, 0x27, 0x59, 0x63, 0x1f, 0xba, 0x8c, 0x5f, 0x7b, 0x2c,
	0xa2, 0xa9, 0x08, 0xa3, 0x85, 0x7e, 0xc7, 0x54, 0xec, 0x6d, 0xa7, 0xc3, 0xf8, 0x28, 0x0d, 0xe1,
	0x13, 0xd8, 0x9f, 0xbb, 0x11, 0x05, 0xa2, 0x00, 0xdb, 0x32, 0x15, 0x7b, 0xc7, 0xe9, 0x2d, 0xe3,
	0x19, 0xd4, 0xb8, 0x80, 0xdd, 0x52, 0x89, 0xa8, 0x43, 0x9b, 0xd3, 0x34, 0x0c, 0x3c, 0x9e, 0xf4,
	0x47, 0x73, 0xd2, 0xcf, 0xb8, 0xdc, 0xc0, 0x0d, 0xc2, 0x74, 0x57, 0x4d, 0x76, 0x8b, 0x21, 0xeb,
	0x25, 0x6c, 0x8f, 0x58, 0xf4, 0x3a, 0x10, 0xd1, 0x22, 0x2e, 0x3d, 0x70, 0x7d, 0x4a, 0x44, 0x76,
	0x9c, 0x64, 0x5d, 0x2b, 0x5d, 0xad, 0x95, 0x6e, 0xbd, 0x80, 0xe3, 0x31, 0xe5, 0xf5, 0x5d, 0xd0,
	0x82, 0x3b, 0xf4, 0xfd, 0x96, 0xb8, 0xc0, 0x53, 0xd8, 0xc9, 0xa9, 0x4b, 0xd9, 0x3c, 0x60, 0xbd,
	0x05, 0xbd, 0x4e, 0xe4, 0xf3, 0x30, 0xe0, 0x84, 0xcf, 0xa0, 0x4d, 0x81, 0x88, 0x18, 0xc5, 0x67,
	0xd2, 0xec, 0xce, 0x10, 0xf3, 0x69, 0xa5, 0x05, 0x3b, 0x29, 0xc4, 0x7a, 0x0c, 0x38, 0x26, 0x91,
	0x4e, 0x30, 0xcd, 0xbe, 0x0f, 0xda, 0x37, 0x4a, 0xf3, 0xc6, 0x4b, 0xeb, 0x1c, 0x0e, 0x4b, 0x38,
	0x99, 0x6c, 0x08, 0x99, 0xfb, 0xa4, 0xc3, 0x8e, 0x9a, 0xbd, 0xe1, 0xe4, 0x2e, 0xfd, 0x0c, 0x38,
	0xd9, 0x20, 0x65, 0x49, 0x5b, 0xdd, 0x50, 0xfb, 0x1e, 0x1c, 0x4e, 0xea, 0x65, 0x5a, 0x16, 0xec,
	0x8d, 0x49, 0xc4, 0x9c, 0xd5, 0x27, 0xbc, 0x82, 0x5e, 0x86, 0x91, 0xa7, 0x43, 0x68, 0xdd, 0xb0,
	0xd9, 0x72, 0xac, 0x5d, 0x27, 0x59, 0xff, 0x57, 0x55, 0x5f, 0x61, 0xef, 0xfd, 0xed, 0xfa, 0xf4,
	0x59, 0x2e, 0x75, 0x45, 0x2e, 0x6d, 0xc3, 0x5c, 0x07, 0xd0, 0xcb, 0x72, 0xc9, 0xd3, 0x3f, 0x82,
	0x83, 0x11, 0xcd, 0x48, 0xd0, 0xfa, 0x06, 0xdc, 0x05, 0x2c, 0xc2, 0x24, 0xf9, 0x29, 0x1c, 0xbd,
	0x4a, 0x5e, 0x83, 0xcc, 0x6d, 0xab, 0x15, 0x4e, 0xe0, 0xb8, 0x86, 0xcd, 0x65, 0x96, 0xe2, 0x9b,
	0xc9, 0xd4, 0xb0, 0x4b, 0x99, 0xe1, 0x9f, 0x16, 0xf4, 0xd2, 0x43, 0x4f, 0x28, 0xfa, 0xc1, 0xa6,
	0x14, 0x3f, 0x72, 0x72, 0x70, 0xa8, 0xe7, 0xed, 0x29, 0xcf, 0xdb, 0x38, 0x69, 0xd8, 0x91, 0x53,
	0x3e, 0x83, 0xb6, 0xec, 0x58, 0x91, 0x5f, 0x1e, 0x58, 0x91, 0x5f, 0x69, 0x2f, 0x8e, 0x01, 0xf2,
	0xbe, 0xe1, 0xfd, 0xc2, 0x6d, 0xab, 0x36, 0xdd, 0x38, 0x6d, 0xde, 0x94, 0x42, 0xef, 0xa0, 0x53,
	0xb8, 0x63, 0x78, 0x5a, 0x2a, 0xb9, 0x72, 0x5f, 0x8c, 0x07, 0x2b, 0x76, 0x73, 0xad, 0x49, 0xb3,
	0xd6, 0x64, 0xad, 0x56, 0xc3, 0xed, 0xc1, 0x2b, 0xd8, 0xaf, 0xbe, 0x36, 0xd8, 0x2f, 0xa5, 0x6f,
	0x7a, 0xc2, 0x0c, 0x6b, 0x1d, 0x44, 0x4a, 0x7f, 0x82, 0x5e, 0xc5, 0x31, 0x68, 0xe6, 0xb4, 0x66,
	0xe3, 0x19, 0xfd, 0x35, 0x88, 0x5c, 0xb7, 0x62, 0xa1, 0xa2, 0x6e, 0xb3, 0x13, 0x8b, 0xba, 0x2b,
	0xfc, 0xf7, 0x65, 0x2b, 0xf9, 0xe5, 0x3e, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x72, 0x4f, 0x12,
	0x42, 0x84, 0x07, 0x00, 0x00,
}
